// ============================================================
// TEMPLATES / TEMPLATES_EN slice — criteria: Junior
// ============================================================
// Bagian dari performance split (rencana-10-10-non-security.md bagian 5.1).
// Sama seperti data.junior.js — dimuat DINAMIS oleh js/lazy-loader.js,
// bukan di <head>. JANGAN declare ulang 'const TEMPLATES'/'TEMPLATES_EN'
// di sini — js/templates.js (file inti) sudah mendeklarasikan keduanya
// sebagai objek kosong.
// ============================================================

Object.assign(TEMPLATES, {
  "3D ANIMATOR": {
    "1": "Pada pertemuan ini, {nama} mempelajari apa itu komputer dan bagian-bagiannya. {nama} juga mempelajari cara menjaga Gadget agar tidak rusak.",
    "2": "Dalam sesi ini, {nama} berlatih mengetik di komputer. Tak hanya itu, {nama} juga mempelajari pentingnya Media Balance.",
    "3": "Pada pertemuan ini, {nama} diperkenalkan dengan Coding sebagai bahasa komputer. Di samping itu, {nama} juga mempelajari pentingnya mengurangi screen time.",
    "4": "Di pertemuan kali ini, {nama} berkenalan dengan Robot. {nama} juga menggerakkan Robot dengan coding.",
    "5": "Pada sesi kali ini, {nama} mempelajari penerapan event dalam coding. Tidak hanya itu, {nama} juga menggerakkan Robot dengan coding.",
    "6": "Pada pertemuan ini, {nama} mempelajari konsep Loop dalam Coding. {nama} juga mengimplementasikan konsep Loop pada game.",
    "7": "Dalam pertemuan kali ini, {nama} mengenal aplikasi ScratchJr. Selain itu, {nama} juga belajar membuat animasi dengan coding.",
    "8": "Pada pertemuan ini, {nama} mengerjakan Coding Challenge - menguji pemahaman materi yang telah dipelajari sejauh ini.",
    "9": "Di sesi ini, {nama} menggunakan mode grid untuk melihat posisi karakter di ScratchJr. {nama} juga membuat animasi roket terbang ke bulan.",
    "10": "Pada pertemuan ini, {nama} mempelajari fungsi kode Message di ScratchJr. Lebih dari itu, {nama} juga membuat game animasi Animal Race.",
    "11": "Pada pertemuan ini, {nama} mempelajari apa itu Internet dan manfaatnya. {nama} juga mempelajari cara melakukan Debugging.",
    "12": "Dalam sesi ini, {nama} belajar sambil bermain dengan shapes. Di samping itu, {nama} juga mempelajari apa saja yang boleh dibagikan ke internet.",
    "13": "Pada pertemuan ini, {nama} mengingat kembali tombol pada Robot. {nama} juga menggerakkan Robot dengan coding.",
    "14": "Di pertemuan kali ini, {nama} berlatih membuat animasi di ScratchJr. Tak hanya itu, {nama} juga membuat animasi Basketball.",
    "15": "Pada sesi kali ini, {nama} membuat proyek akhir di ScratchJr - menggabungkan semua konsep animasi dan coding yang telah dipelajari menjadi sebuah karya yang utuh.",
    "16": "Pada pertemuan ini, {nama} mengerjakan Coding Challenge sebagai evaluasi materi ScratchJr dan pengembangan game.",
    "17": "Dalam pertemuan kali ini, {nama} mempelajari apa itu game tiga dimensi (3D Game). {nama} juga belajar membuat 3D Game dengan Kodu.",
    "18": "Pada pertemuan ini, {nama} berlatih membuat 3D Game. Selain itu, {nama} juga membuat dunia bawah air di Kodu.",
    "19": "Di sesi ini, {nama} mengenal konsep Conditional dalam coding. {nama} juga membuat coding pada sensor Robot.",
    "20": "Pada pertemuan ini, {nama} berlatih membuat 3D Game. Tak hanya itu, {nama} juga membuat Racing Game di Kodu.",
    "21": "Pada pertemuan ini, {nama} berlatih membuat 3D Game. Di samping itu, {nama} juga melengkapi coding pada project yang disediakan.",
    "22": "Dalam sesi ini, {nama} mempelajari perkenalan dengan sensor baru pada Robot. {nama} juga belajar memrogram sensor tepuk tangan dan suara.",
    "23": "Pada pertemuan ini, {nama} membuat design plan untuk project akhir 3D Game. Tidak hanya itu, {nama} juga membuat proyek akhir 3D Game dengan Kodu.",
    "24": "Di pertemuan kali ini, {nama} mengerjakan Coding Challenge - ujian akhir untuk mengevaluasi seluruh pemahaman materi 3D Animator."
  },
  "Website Designer": {
    "1": "Pada sesi kali ini, {nama} belajar konsep Conditional Loop dalam coding. Selain itu, {nama} juga menggerakkan robot dengan coding.",
    "2": "Pada pertemuan ini, {nama} mempelajari apa itu Virtual Reality (VR). {nama} juga belajar membuat VR dengan Delightex.",
    "3": "Dalam pertemuan kali ini, {nama} berlatih membuat Virtual Reality. Tak hanya itu, {nama} juga membuat kota virtual di Delightex.",
    "4": "Pada pertemuan ini, {nama} belajar konsep Function dalam coding. Di samping itu, {nama} juga menggerakkan robot dengan konsep Function.",
    "5": "Di sesi ini, {nama} mempelajari apa itu Augmented Reality (AR). {nama} juga belajar mendesain AR dengan Delightex.",
    "6": "Pada pertemuan ini, {nama} berlatih membuat Virtual Reality. Tidak hanya itu, {nama} juga membuat rumah virtual di Delightex.",
    "7": "Pada pertemuan ini, {nama} menyelesaikan project akhir Virtual Reality menggunakan Delightex - menggabungkan semua elemen yang telah dibuat menjadi pengalaman VR yang lengkap.",
    "8": "Dalam sesi ini, {nama} mengerjakan Coding Challenge sebagai evaluasi pemahaman materi yang telah dipelajari.",
    "9": "Pada pertemuan ini, {nama} berlatih membuat desain & coding AR. {nama} juga membuat AR aquarium dengan Delightex.",
    "10": "Di pertemuan kali ini, {nama} memulai project akhir AR. Selain itu, {nama} juga mendesain project \"All about me\" di Delightex.",
    "11": "Pada sesi kali ini, {nama} menyelesaikan project akhir Augmented Reality - melengkapi semua scene, elemen interaktif, dan konten personal menjadi pengalaman AR yang utuh.",
    "12": "Pada pertemuan ini, {nama} mengenal apa itu Website. {nama} juga belajar membuat Website sederhana.",
    "13": "Dalam pertemuan kali ini, {nama} mulai mengerjakan project akhir Website. Lebih dari itu, {nama} juga menambahkan layout biodata & project.",
    "14": "Pada pertemuan ini, {nama} melanjutkan project akhir Website. {nama} juga menambahkan halaman ke dalam Website.",
    "15": "Di sesi ini, {nama} melanjutkan project Website. Di samping itu, {nama} juga menambahkan button pada Website.",
    "16": "Pada pertemuan ini, {nama} menyelesaikan dan menerbitkan website. {nama} juga membuat presentasi project."
  },
  "Virtual World Maker": {
    "1": "Pada pertemuan ini, {nama} mengingat kembali Coding sebagai bahasa komputer. Di samping itu, {nama} juga berlatih membuat coding sesuai algoritma yang benar.",
    "2": "Pada pertemuan ini, {nama} memahami pengaruh Screen Time dan Gadget Addiction. {nama} juga mengingat kembali apa itu Event dalam Coding.",
    "3": "Dalam sesi ini, {nama} mempelajari cara mencegah dan mengatasi Cyber Bullying. Tidak hanya itu, {nama} juga mengingat kembali apa itu Loop dalam coding.",
    "4": "Pada pertemuan ini, {nama} belajar membuat animasi di Scratch. {nama} juga mengeksplor bagian-bagian di Scratch.",
    "5": "Di pertemuan kali ini, {nama} mengingat kembali konsep Conditional dalam Coding. Selain itu, {nama} juga berlatih menggerakkan karakter dengan code If.",
    "6": "Pada sesi kali ini, {nama} belajar pentingnya Media Balance. {nama} juga memprogram robot dengan platform baru.",
    "7": "Pada pertemuan ini, {nama} mempelajari perbedaan komunikasi langsung dengan online. Lebih dari itu, {nama} juga mengenal dan mengendalikan Drone secara virtual.",
    "8": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya.",
    "9": "Dalam pertemuan kali ini, {nama} mempelajari Bug pada suatu program. {nama} juga membuat Bug Hunter game menggunakan konsep Conditional.",
    "10": "Pada pertemuan ini, {nama} menggunakan \"Glide\" untuk menggerakkan sprite. Di samping itu, {nama} juga membuat Beetle Race Game di Scratch.",
    "11": "Di sesi ini, {nama} mengingat kembali tentang Copyright. {nama} juga mengaplikasikan kode Function di coding game.",
    "12": "Pada pertemuan ini, {nama} mengingat kembali apa itu Function dalam coding. Tak hanya itu, {nama} juga mengimplementasikan konsep Function pada Robot.",
    "13": "Pada pertemuan ini, {nama} mempelajari pentingnya tetap berusaha & pantang menyerah. {nama} juga mengenal Conditional Loop dalam coding.",
    "14": "Dalam sesi ini, {nama} mengenal Spam dan cara menghindarinya. Selain itu, {nama} juga menggunakan kode Forever dalam coding.",
    "15": "Pada pertemuan ini, {nama} mempelajari apa itu Micro:bit. {nama} juga belajar memprogram Micro:bit dengan kode Forever.",
    "16": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya.",
    "17": "Di pertemuan kali ini, {nama} mengingat kembali apa itu Virtual Reality (VR). Tak hanya itu, {nama} juga membuat pameran hewan dengan VR.",
    "18": "Pada sesi kali ini, {nama} menggunakan function dalam VR. Di samping itu, {nama} juga membuat VR \"Finding Animal\".",
    "19": "Pada pertemuan ini, {nama} mempelajari perkembangan teknologi dalam kehidupan manusia. {nama} juga mengenal Variable dalam coding.",
    "20": "Dalam pertemuan kali ini, {nama} mengenal aplikasi untuk membantu dalam perjalanan. Tidak hanya itu, {nama} juga membuat VR City Tour.",
    "21": "Pada pertemuan ini, {nama} mengenal Operator dalam coding. {nama} juga mengaplikasikan kode Operator ke dalam Math Game.",
    "22": "Di sesi ini, {nama} mengenal Hoax dan cara menghindarinya. Selain itu, {nama} juga membuat multiple diorama dalam VR.",
    "23": "Pada pertemuan ini, {nama} melanjutkan project multiple diorama sebelumnya. {nama} juga mempresentasikan Solar System VR.",
    "24": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya."
  },
  "Little Programmer": {
    "1": "Dalam sesi ini, {nama} mengenal Cloud Storage. {nama} juga mengaplikasikan konsep Variable pada Micro:Bit.",
    "2": "Pada pertemuan ini, {nama} mempelajari internet of Things untuk membantu kehidupan. Di samping itu, {nama} juga mengenal List dalam coding.",
    "3": "Di pertemuan kali ini, {nama} mengenal apa itu Broadcast dalam Coding. {nama} juga membuat animasi Greeting Card dengan kode Broadcast.",
    "4": "Pada sesi kali ini, {nama} memahami pengertian dari Jejak Digital. Tak hanya itu, {nama} juga mengkombinasikan robot Maqueen dengan Micro:bit.",
    "5": "Pada pertemuan ini, {nama} memahami komunitas dan perkembangannya. {nama} juga membuat animasi Lost in Space di Scratch.",
    "6": "Dalam pertemuan kali ini, {nama} berlatih membuat animasi di Scratch. Selain itu, {nama} juga membuat Flying Game dengan coding.",
    "7": "Pada pertemuan ini, {nama} mengenal Virus pada komputer dan cara mengatasinya. {nama} juga membuat game animasi menggunakan List.",
    "8": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya.",
    "9": "Di sesi ini, {nama} mengingat kembali cara membuat AR. Tak hanya itu, {nama} juga membuat quiz di dalam AR.",
    "10": "Pada pertemuan ini, {nama} mengenal apa itu Operating System. Di samping itu, {nama} juga membuat coding Wireless Controller pada Micro:bit dan Maqueen.",
    "11": "Pada pertemuan ini, {nama} belajar menggunakan Clone di Scratch. {nama} juga membuat animasi Clone War.",
    "12": "Dalam sesi ini, {nama} membuat AR tentang bangunan bersejarah di berbagai negara. Tidak hanya itu, {nama} juga mempelajari bangunan bersejarah di dunia.",
    "13": "Pada pertemuan ini, {nama} melanjutkan AR tentang bangunan bersejarah di berbagai negara. {nama} juga memberikan coding kepada karakter yang ada.",
    "14": "Di pertemuan kali ini, {nama} mengenal konsep Addictive Design. Selain itu, {nama} juga membuat game Create Your Own World - Part 1.",
    "15": "Pada sesi kali ini, {nama} melanjutkan pembuatan game Create Your Own World - menambahkan lebih banyak elemen, menyempurnakan gameplay, dan menyelesaikan bagian kedua dari proyek game ini.",
    "16": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya.",
    "17": "Pada pertemuan ini, {nama} mengenal apa itu kecerdasan buatan. {nama} juga mempelajari text coding dan bahasa Python.",
    "18": "Dalam pertemuan kali ini, {nama} mempelajari internet sebagai sumber informasi dan tempat belajar. Lebih dari itu, {nama} juga mengaplikasikan Operator & Variable pada Robot.",
    "19": "Pada pertemuan ini, {nama} mulai membuat Soccer Game menggunakan Scratch - menyiapkan tampilan lapangan, karakter pemain, dan mekanik dasar permainan.",
    "20": "Di sesi ini, {nama} melanjutkan membuat Soccer Game dengan Scratch. {nama} juga memainkan game yang telah dibuat.",
    "21": "Pada pertemuan ini, {nama} menentukan ide untuk membuat game sendiri. Di samping itu, {nama} juga mengumpulkan asset game.",
    "22": "Pada pertemuan ini, {nama} membuat game sendiri. {nama} juga menyusun layout game dan coding start layout.",
    "23": "Dalam sesi ini, {nama} membuat game sendiri. Tak hanya itu, {nama} juga menambahkan coding, life, score dan next level.",
    "24": "Pada pertemuan ini, {nama} melakukan launch game. {nama} juga melakukan persiapan presentasi untuk pertemuan berikutnya."
  }
});
Object.assign(TEMPLATES_EN, {
  "3D ANIMATOR": {
    "1": "In today's class, {nama} learned about what a computer is and its different parts. {nama} also learned how to take care of gadgets properly so they last longer.",
    "2": "Today, {nama} practiced typing on a computer and learned about the importance of balancing screen time with other activities.",
    "3": "In this session, {nama} was introduced to coding as a computer language. {nama} also learned why it's important to reduce unnecessary screen time.",
    "4": "Today, {nama} got to meet a robot! {nama} learned how to make the robot move using simple coding commands.",
    "5": "In today's class, {nama} learned about coding events - actions that trigger things to happen in a program. {nama} also practiced moving a robot using coding.",
    "6": "Today, {nama} learned about loops in coding - a way to repeat actions automatically. {nama} then applied this concept in a fun game.",
    "7": "In this session, {nama} was introduced to ScratchJr, a beginner-friendly coding app. {nama} learned how to create simple animations using code.",
    "8": "{nama} reviewed everything learned so far and completed Coding Challenge as a fun test of their skills.",
    "9": "Today, {nama} learned how to use the grid view in ScratchJr to track a character's position on screen. {nama} then created a rocket animation flying to the moon!",
    "10": "In this class, {nama} learned how the Message block works in ScratchJr to make characters communicate. {nama} then built an Animal Race animation game.",
    "11": "Today, {nama} learned what the internet is and how it can be useful. {nama} also learned what debugging means - finding and fixing mistakes in a program.",
    "12": "In this session, {nama} had fun learning with different shapes. {nama} also learned what kind of information is safe to share online.",
    "13": "Today, {nama} remembered how to use the robot's buttons and practiced making the robot move using coding commands.",
    "14": "In this class, {nama} practiced creating animations in ScratchJr and successfully built a Basketball animation.",
    "15": "Today, {nama} worked on a final animation project in ScratchJr, combining all the skills learned so far.",
    "16": "{nama} reviewed previous lessons and completed Coding Challenge to test their understanding.",
    "17": "In this session, {nama} learned what a 3D game is and how it differs from regular games. {nama} started building a 3D world using Kodu.",
    "18": "Today, {nama} continued practicing 3D game creation. {nama} built an exciting underwater 3D world in Kodu.",
    "19": "In this class, {nama} learned about conditional statements in coding - rules that help a program make decisions. {nama} applied this to program a robot sensor.",
    "20": "Today, {nama} continued practicing 3D game development and created a fun Racing Game inside Kodu.",
    "21": "In this session, {nama} practiced 3D game creation and completed the coding for a given project.",
    "22": "Today, {nama} was introduced to a new robot sensor. {nama} learned how to program the clap and sound sensors on the robot.",
    "23": "In this class, {nama} created a design plan for their final 3D game project and then started building it in Kodu.",
    "24": "{nama} reviewed lessons 17–23 and completed Coding Challenge as the final assessment for this unit."
  },
  "Website Designer": {
    "1": "Today, {nama} reviewed Conditional Loop coding and practised controlling a robot.",
    "2": "In this session, {nama} was introduced to Virtual Reality (VR) and started learning how to build VR experiences using Delightex.",
    "3": "Today, {nama} practised building a Virtual Reality environment and created a virtual city in Delightex.",
    "4": "In this class, {nama} learned about Functions in coding and applied them to control a robot.",
    "5": "Today, {nama} was introduced to Augmented Reality (AR) and started designing AR experiences in Delightex.",
    "6": "In this session, {nama} practised VR creation and built a virtual house in Delightex.",
    "7": "Today, {nama} completed a final Virtual Reality project using Delightex.",
    "8": "{nama} completed Coding Challenge.",
    "9": "In this class, {nama} practised designing and coding AR experiences and built an AR aquarium in Delightex.",
    "10": "Today, {nama} started the final AR project - designing an 'All About Me' experience in Delightex.",
    "11": "In this session, {nama} finished the final AR project - completing all the scenes, interactive elements, and personal content.",
    "12": "Today, {nama} was introduced to how Websites work and learned how to build a simple one using basic HTML.",
    "13": "In this class, {nama} started working on a final Website project - setting up the structure and adding a personal profile section and a project showcase layout.",
    "14": "Today, {nama} continued building the Website project - adding new pages and expanding the content with more sections and details.",
    "15": "In this session, {nama} continued building the Website and added interactive buttons to improve the user experience and navigation between pages.",
    "16": "Today, {nama} finished and published the website, then prepared a project presentation."
  },
  "Virtual World Maker": {
    "1": "Today, {nama} remembered that coding is a language for computers and practised writing code in the correct order using an algorithm.",
    "2": "In this session, {nama} explored the effects of screen time and gadget addiction, and reviewed how Events work in coding.",
    "3": "Today, {nama} learned about cyber bullying and reviewed how Loops work in coding.",
    "4": "In this class, {nama} practised making animations in Scratch and explored different areas of the Scratch interface.",
    "5": "Today, {nama} reviewed Conditional statements in coding and practised moving a character using If-blocks.",
    "6": "In this session, {nama} learned about the importance of Media Balance and programmed a robot using a new platform.",
    "7": "Today, {nama} learned about the differences between face-to-face and online communication, and explored virtual drone control.",
    "8": "{nama} reviewed all previous lessons and completed the exam.",
    "9": "In this class, {nama} learned what a Bug is in a program and built a Bug Hunter game using Conditional logic.",
    "10": "Today, {nama} used the Glide feature in Scratch to create moving sprites and built a Beetle Race game.",
    "11": "In this session, {nama} revisited the concept of Copyright and applied Function blocks in a coding game.",
    "12": "Today, {nama} reviewed what Functions are in coding and applied the concept to control a robot.",
    "13": "In this class, {nama} was reminded of the importance of perseverance and was introduced to Conditional Loops in coding.",
    "14": "Today, {nama} learned about spam and how to recognise it, and practised using the Forever loop in coding.",
    "15": "In this session, {nama} was introduced to Micro:bit and learned how to program it using the Forever block.",
    "16": "{nama} reviewed all previous lessons and completed the exam.",
    "17": "Today, {nama} reviewed what Virtual Reality (VR) is and built an animal exhibition in a VR environment.",
    "18": "In this class, {nama} used Functions in VR and created a 'Finding Animal' game.",
    "19": "Today, {nama} explored how technology has developed over time and was introduced to Variables in coding.",
    "20": "In this session, {nama} explored travel apps and built a VR City Tour experience.",
    "21": "Today, {nama} learned about Operators in coding and applied them to build a Math game.",
    "22": "In this class, {nama} learned about hoaxes and how to avoid being fooled. {nama} also built a multi-scene diorama in VR.",
    "23": "Today, {nama} continued the multi-scene diorama project and presented a Solar System VR to the class.",
    "24": "{nama} reviewed all previous lessons and completed the final exam."
  },
  "Little Programmer": {
    "1": "Today, {nama} learned about Cloud Storage - how we save files online. {nama} also applied the concept of Variables on a Micro:bit device.",
    "2": "In this session, {nama} explored how the Internet of Things (IoT) helps people in everyday life. {nama} was also introduced to Lists in coding.",
    "3": "Today, {nama} learned what Broadcast means in coding and created a Greeting Card animation using the Broadcast block.",
    "4": "In this class, {nama} learned about Digital Footprints - the trail we leave when we use the internet. {nama} also combined a Maqueen robot with a Micro:bit.",
    "5": "Today, {nama} explored what a community is and how it grows. {nama} also created a 'Lost in Space' animation in Scratch.",
    "6": "In this session, {nama} practised making animations in Scratch and built a Flying Game using code.",
    "7": "Today, {nama} learned about computer viruses and how to stay safe. {nama} also created an animation game using Lists.",
    "8": "{nama} reviewed all previous lessons and completed the written exam and coding test.",
    "9": "In this class, {nama} reviewed how to make AR experiences and created a quiz inside an AR scene.",
    "10": "Today, {nama} learned what an Operating System is and built a Wireless Controller using a Micro:bit and Maqueen robot.",
    "11": "In this session, {nama} learned how to use Clone in Scratch and built a Clone War animation.",
    "12": "Today, {nama} created an AR experience about famous landmarks from around the world and learned interesting facts about them.",
    "13": "In this class, {nama} continued building the World Landmarks AR and added coding to make the characters interactive.",
    "14": "Today, {nama} was introduced to Addictive Design - how games and apps are designed to keep us engaged. {nama} started building a 'Create Your Own World' game - Part 1.",
    "15": "In this session, {nama} continued building the 'Create Your Own World' game - Part 2.",
    "16": "{nama} reviewed all previous lessons and completed the written exam and coding test.",
    "17": "Today, {nama} was introduced to Artificial Intelligence (AI) and started exploring text-based coding using Python.",
    "18": "In this class, {nama} learned how the internet can be a great source of learning. {nama} also applied Operators and Variables to control a robot.",
    "19": "Today, {nama} used Scratch to build Part 1 of a Soccer Game.",
    "20": "In this session, {nama} continued building the Soccer Game in Scratch and got to play the finished version.",
    "21": "Today, {nama} came up with an idea for their own game and collected all the assets needed.",
    "22": "In this class, {nama} started building their game - setting up the layout and coding the start screen.",
    "23": "Today, {nama} continued developing their game by adding code, lives, a score counter, and the next level.",
    "24": "In this final session, {nama} launched the game and prepared a presentation for the next meeting."
  }
});
