// ============================================================
// TEMPLATES / TEMPLATES_EN slice — criteria: Teens
// ============================================================
// Bagian dari performance split (rencana-10-10-non-security.md bagian 5.1).
// Sama seperti data.teens.js — dimuat DINAMIS oleh js/lazy-loader.js,
// bukan di <head>. JANGAN declare ulang 'const TEMPLATES'/'TEMPLATES_EN'
// di sini — js/templates.js (file inti) sudah mendeklarasikan keduanya
// sebagai objek kosong.
// ============================================================

Object.assign(TEMPLATES, {
  "AI Computer Vision": {
    "1": "Dalam pertemuan kali ini, {nama} mempelajari konsep Computer Vision. {nama} juga menggunakan OpenCV Library, mempelajari konsep Image Processing, mempelajari teknik blurring menggunakan OpenCV, dan mempelajari Image Manipulation menggunakan OpenCV.",
    "2": "Pada pertemuan ini, {nama} mempelajari konsep dan kebutuhan pembuatan model computer vision. {nama} juga mempelajari arsitektur model CNN, mempelajari Tools Tensorflow untuk melatih model, dan mempelajari Tools Tensorflow untuk melatih model.",
    "3": "Di sesi ini, {nama} mempelajari sumber pengumpulan dataset Computer Vision. {nama} juga mempelajari cara penggunaan Tensorflow dataset, mempelajari cara melakukan data augmentasi menggunakan Image Data Generator, dan membuat project Horse and Human Classification.",
    "4": "Pada pertemuan ini, {nama} menggunakan Pre-trained model dan Machine Learning Framework. {nama} juga membuat aplikasi face detection di gambar, dan membuat aplikasi face detection di video.",
    "5": "Pada pertemuan ini, {nama} mempelajari arsitektur model Single Shot Detector (SSD). {nama} juga dapat membuat project Object Detection menggunakan Model SSD, dan mengimplementasikan project object Detector baik itu di gambar atau di video.",
    "6": "Dalam sesi ini, {nama} mempelajari konsep Object Tracking dan cara kerjanya. {nama} juga mempelajari perbedaan Object Detection dan Tracking, mempelajari konsep Euclidean Distance Tracker, mempelajari konsep countour detection, dan mempelajari konsep image thresholding.",
    "7": "Pada pertemuan ini, {nama} mengaplikasikan penggunaan Euclidean Distance Tracker Class. {nama} juga menambahkan Unique Identification dari object yang terdeteksi untuk proses tracking, dan menambahkan \"marker\" untuk object yang sedang di track.",
    "8": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya.",
    "9": "Di pertemuan kali ini, {nama} mempelajari konsep tentang Optical Character Recognition (OCR). {nama} juga mengatahui cara manipulasi image processing untuk OCR, menggunakan library easyocr untuk ANPR, dan mendalami konsep image masking dan contours detection.",
    "10": "Pada sesi kali ini, {nama} mempelajari implementasi lain OCR / OCR Handwritting. {nama} juga menggunakan pre-trained model menggunakan keras library, dan menggunakan Image Processing untuk OCR Handwritting.",
    "11": "Pada pertemuan ini, {nama} diperkenalkan dengan Mediapipe Library untuk landmark detection. {nama} juga menggunakana Mediapipe untuk Holistic Tracking, mendalami konsep Image Manipulation di Video Frames, dan membuat project Virtual Painter.",
    "12": "Dalam pertemuan kali ini, {nama} mencari posisi landmark tangan menggunakan method enumerate(). {nama} juga mempelajari klasifikasi landmark pada tangan, menginisialisasi mode pada project Virtual Painter (Selection dan Drawing), dan finishing project dengan teknis Video Frame Masking.",
    "13": "Pada pertemuan ini, {nama} mempelajari anatomi Face Mesh di Mediapipe. {nama} juga menggambar landmark menggunakan Face Mesh Landmark model, dan membuat project Pig Face Filter menggunakan Mediapipe.",
    "14": "Di sesi ini, {nama} mempelajari implementasi dari Face Mesh Landmark. {nama} juga mempelajari Facial Area yang ada di dalam Mediapipe, membuat project Face FIlter Dragon Project, dan membuat class Face Mesh untuk mendeteksi Facial Area.",
    "15": "Pada pertemuan ini, {nama} mengidentifikasi apakah mulut terbuka atau tidak. {nama} juga mengidentifikasi apakah mulut terbuka atau tidak, dan melakukan Video masking untuk menempelkan efek filter ke dalam frames.",
    "16": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya."
  },
  "Python for Data Science": {
    "1": "Pada pertemuan ini, {nama} mempelajari konsep Artificial Intelligence. {nama} juga mendapatkan pengenalan Python Programming, melakukan setup installation untuk Python, mempelajari syntax basic Python, dan memahami Variable / Datatype / Operator / Input menggunakan Python.",
    "2": "Dalam sesi ini, {nama} mempelajari Struktur Data dalam Python. {nama} juga memahami penggunaan Daftar (1D, 2D), memahami metode untuk memanipulasi daftar, memahami penggunaan Tuples, dan membuat Proyek Pembuat Kata Sandi.",
    "3": "Pada pertemuan ini, {nama} memahami konsep dictionary. {nama} juga mempelajari cara membuat dictionary dan metode yang digunakan dalam dictionaries, menggabungkan beberapa struktur data menjadi satu, dan membuat proyek Dictionary Film.",
    "4": "Di pertemuan kali ini, {nama} memahami konsep looping. {nama} juga memahami contoh penggunaan loops for dalam Python, memahami contoh penggunaan loops while di Python, teknik looping satu baris, dan looping exercise.",
    "5": "Pada sesi kali ini, {nama} memahami konsep conditions dalam Python. {nama} juga memahami konsep conditions disi bersarang di Python, menggabungkan conditions dengan perulangan, dan membuat Proyek Jumbled Word.",
    "6": "Pada pertemuan ini, {nama} memahami functions  dalam Python. {nama} juga mempelajari functions bawaan dalam Python, functions yang ditentukan pengguna dalam Python, scope rules di Python, dan membuat Chatbot Discord menggunakan Discord.py.",
    "7": "Dalam pertemuan kali ini, {nama} memahami konsep OOP. {nama} juga membedakan Object, Class, Method, dan Property, memahami konsep inheritance dalam OOP, dan membuat game sederhana menggunakan OOP.",
    "8": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya.",
    "9": "Pada pertemuan ini, {nama} mempelajari konsep Sorting. {nama} juga memahami cara kerja algoritma bubble sort dan insertion sort, menerapkan kode untuk algoritma bubble sort dan insertion sort, memahami cara kerja algoritma pencarian linear, dan menerapkan kode untuk algoritma pencarian linier.",
    "10": "Di sesi ini, {nama} memahami apa itu Python libraries dan contoh-contohnya. {nama} juga memahami cara memasang Python libraries, menggunakan Numpy library, membuat Numpy arrays (1D, 2D, 3D) dan memanipulasinya, dan membuat  TicTacToe project menggunakan Numpy.",
    "11": "Pada pertemuan ini, {nama} memahami data dan jenis data. {nama} juga memahami pentingnya data, memahami mekanisme pengumpulan data, pengenalan alat bantu pemrosesan data (Google Colab), dan memahami cara memanipulasi dataframe menggunakan pandas.",
    "12": "Pada pertemuan ini, {nama} memahami cara mendefinisikan pertanyaan bisnis. {nama} juga memahami alur analisis data, membuat proyek analisis data e-commerce, memahami mekanisme penilaian data, dan memahami mekanisme pembersihan data.",
    "13": "Dalam sesi ini, {nama} memahami tahapan data analysis eksploratori (EDA) dalam data analysis. {nama} juga menerapkan teknik pengelompokan data, memahami konsep data visualization yang efektif, mempelajari cara mengubah set data, dan menjawab pertanyaan bisnis.",
    "14": "Pada pertemuan ini, {nama} memahami hubungan antara  probability dan artificial intelligence. {nama} juga memahami konsep dasar probability, memecahkan masalah probability sederhana seperti koin dan dadu, memahami konsep distribusi, dan memecahkan masalah ulang tahun.",
    "15": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya.",
    "16": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya."
  },
  "AI Machine Learning": {
    "1": "Pada pertemuan ini, {nama} mempelajari hubungan AI, Machine Learning, dan Deep Learning. {nama} juga mempelajari apa itu Machine Learning dan kategorinya, mempelajari cara kerja Machine Learning, dan menggunakan Pandas sebagai library untuk manipulasi dataframe.",
    "2": "Dalam sesi ini, {nama} mempelajari cara kerja Classification. {nama} juga mengolah dan Mempersiapkan dataset Iris Flower, dan membaca dan Memvisualisasikan dataset menggunakan Seaborn.",
    "3": "Pada pertemuan ini, {nama} mempelajari cara kerja Algoritma KNN Classifier. {nama} juga melakukan training model menggunakan algoritma KNN, melakukan model evaluation, melakukan proses parameter tuning dari model yang sudah dilatih, dan melakukan prediksi dari model yang sudah dibuat.",
    "4": "Di pertemuan kali ini, {nama} mempelajari konsep Natural Language Processing (NLP). {nama} juga mempelajari bagaimana cara NLP bekerja, explorasi NLP menggunakan ChatGPT, dan menggunakan NLTK untuk proses NLP di Python.",
    "5": "Pada sesi kali ini, {nama} mempelajari proses yang ada di dalam Sentiment Analysis. {nama} juga mempelajari konsep Feature Extractin dan Vectorization.",
    "6": "Pada pertemuan ini, {nama} mempelajari bagaimana cara kerja algortima Random Forest Classifier. {nama} juga mempelajari bagaimana cara kerja Naive bayes Classifier bekerja, meningkatkan skor akurasi model yang sudah di latih, dan membuat prediksi berdasarkan model sentiment analysis yang sudah dibuat.",
    "7": "Dalam pertemuan kali ini, {nama} mengimplementasikan penggunaan lain NLP. {nama} juga membuat project Fake News Detection menggunakan konsep NLP, membandingkan model Classification dan Regression, dan memahami penggunaan algoritma Logistic Regression.",
    "8": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya.",
    "9": "Pada pertemuan ini, {nama} mempelajari konsep Time Series Forecasting. {nama} juga mempelajari bagaimana konsep fungsi linear, mempelajari cara kerja algoritma Linear Regression, dan membuat project Population Prediction menggunakan model Linear Regression.",
    "10": "Di sesi ini, {nama} mempelajari konsep cara kerja Sales Forecasting. {nama} juga membuat project Sales Prediction, menggunakan library Plotly untuk VIsualisasi Data, memahami konsep Feature Engineering, dan membuat Feature data waktu berdasarkan Feature yang lain.",
    "11": "Pada pertemuan ini, {nama} mempelajari konsep Rolling Windows untuk investigasi data. {nama} juga mempelajari konsep Exponentially Weighted Moving Average, mempelajari konsep Logarithmic Transformation, mempelajari Konsep Neural Network, dan membuat prediksi menggukan model neural network.",
    "12": "Pada pertemuan ini, {nama} memahami konsep Unsupervised Learning. {nama} juga mengidentifikasi jenis-jenis Unsupervised Learning, memahami konsep Clustering menggunakan algoritma K-Means, dan membuat project Customer Segmentation.",
    "13": "Dalam sesi ini, {nama} memahami konsep Recommender System. {nama} juga mengidentifikasi jenis-jenis Recommender System, memahami cara kerja content based filtering dan collaborative filtering, dan menerapkannya pada Course Recommendation System.",
    "14": "Pada pertemuan ini, {nama} memahami konsep detail Unsupervised Anomaly Detection. {nama} juga memahami metode untuk Anomaly Detection, memahami cara kerja algoritma isolated forest, dan membuat project credit card fraud detection.",
    "15": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya.",
    "16": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya."
  },
  "JavaScript Developer": {
    "1": "Pada pertemuan ini, {nama} mempelajari apa itu coding beserta cangkupannya. {nama} juga mempelajari bahasa pemrograman JavaScript, dan mempelajari apa itu algoritma.",
    "2": "Di sesi ini, {nama} mempelajari tentang hoax dan mengidentifikasi hoax. {nama} juga mempelajari konsep variabel dan tipe data.",
    "3": "Pada pertemuan ini, {nama} mempelajari konsep operator dalam coding. Tak hanya itu, {nama} juga memperdalam konsep operator aritmatika dan penugasan.",
    "4": "Pada pertemuan ini, {nama} mempelajari cara mengatasi Cyberbullying. Di samping itu, {nama} juga mempelajari konsep array.",
    "5": "Dalam sesi ini, {nama} memahami konsep conditional dalam coding. {nama} juga belajar menggunakan operator comparison dan logical.",
    "6": "Pada pertemuan ini, {nama} membuat kehidupan seimbang. Tidak hanya itu, {nama} juga memahami conditional dengan switch statement dan ternary operator.",
    "7": "Di pertemuan kali ini, {nama} memahami proses penyelesaian masalah. {nama} juga memahami loop dalam coding.",
    "8": "Pada sesi kali ini, {nama} melakukan review seluruh materi dari pertemuan 1 hingga 7 sebagai persiapan menghadapi ujian JavaScript Developer.",
    "9": "Pada pertemuan ini, {nama} memahami nested for loop. Selain itu, {nama} juga memahami conditional loop.",
    "10": "Dalam pertemuan kali ini, {nama} membuat beberapa program menggunakan JavaScript untuk mempraktikkan konsep-konsep yang telah dipelajari sejauh ini.",
    "11": "Pada pertemuan ini, {nama} memahami manipulasi foto dan video. {nama} juga memahami function dalam coding.",
    "12": "Di sesi ini, {nama} belajar tentang konsep parameter pada function - bagaimana cara mengirim data ke dalam sebuah function agar bisa digunakan secara dinamis.",
    "13": "Pada pertemuan ini, {nama} mempelajari tentang hak cipta dan menghargai hak cipta suatu karya. Lebih dari itu, {nama} juga mempelajari scope dalam JavaScript.",
    "14": "Pada pertemuan ini, {nama} mempelajari cara bereaksi terhadap breaking news. {nama} juga memahami return statement dalam JavaScript, dan menggunakan looping dengan  for each.",
    "15": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya.",
    "16": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya."
  },
  "Web Developer Teens": {
    "1": "Pada pertemuan ini, {nama} diperkenalkan dengan Website. {nama} juga mendapatkan pengenalan HTML, dan memahami tag Heading, Paragraf, Break, Bold, Italic, Underline dalam HTML.",
    "2": "Dalam sesi ini, {nama} diperkenalkan dengan CSS (Cascading Style Sheet). {nama} juga mempelajari CSS Box Model dan komponennya, memahami konsep selector pada CSS, dan menerapkan CSS untuk membuat dan menata bagian header pada website.",
    "3": "Pada pertemuan ini, {nama} memahami dan menerapkan display flex dalam tata letak website. {nama} juga mempelajari teknik efektif untuk menata gambar pada website, dan menambahkan cards untuk product pada website.",
    "4": "Di pertemuan kali ini, {nama} memahami struktur tabel dalam HTML. {nama} juga memahami atribut Colspan dan Rowspan dalam tabel HTML, dan menambahkan tabel ke website.",
    "5": "Pada sesi kali ini, {nama} memahami dan menerapkan List dalam HTML. {nama} juga mempelajari cara membuat button dalam HTML, dan menambahkan pricing table di website.",
    "6": "Pada pertemuan ini, {nama} memahami konsep link termasuk Hyperlink dan Anchor Link. {nama} juga memahami perbedaan Absolute dan Relative URL, dan menambahkan halaman About Us pada website.",
    "7": "Dalam pertemuan kali ini, {nama} mempelajari konsep menambah icon dengan Font Awesome. Lebih dari itu, {nama} juga menambahkan footer dengan gradient color pada website.",
    "8": "Pada pertemuan ini, {nama} menerapkan Google Font dalam website. {nama} juga mempelajari prinsip responsive website, dan mengunggah situs web ke internet.",
    "9": "Di sesi ini, {nama} diperkenalkan dengan JavaScript dalam Dokumen HTML. {nama} juga memahami HTML DOM (Document Object Model), bekerja dengan Metode DOM, dan membuat Halaman Blog dengan JavaScript dan HTML.",
    "10": "Pada pertemuan ini, {nama} memahami konsep event pada DOM. {nama} juga mulai membuat project website Blog.",
    "11": "Pada pertemuan ini, {nama} menambahkan elemen video dan audio ke  HTML5. {nama} juga menyematkan konten media eksternal, dan melanjutkan pembuatan website.",
    "12": "Dalam sesi ini, {nama} mempelajari  HTML Form untuk interaksi pengguna. {nama} juga menggunakan form Elements : Form, Input, Label, Text Area, dan Select tag, form Attributes di HTML, dan membuat website formulir.",
    "13": "Pada pertemuan ini, {nama} menjelajahi Jenis Tag Input. {nama} juga memahami Atribut Input, dan melanjutkan Formulir Halaman Web.",
    "14": "Di pertemuan kali ini, {nama} menambahkan CSS pada Form. {nama} juga kirimkan data formulir ke Email, dan melanjutkan Website.",
    "15": "Pada sesi kali ini, {nama} melakukan submit  data form ke email. {nama} juga membuat Modal dengan HTML,CSS, dan JavaScript, dan melanjutkan Website.",
    "16": "Pada pertemuan ini, {nama} membuat Manual dan Autoplay Image Sliders. {nama} juga memahami metode forEach, dan cek pemahaman 2.",
    "17": "Dalam pertemuan kali ini, {nama} menjelajahi tools untuk membuat Blob, Background, dan Waves. Di samping itu, {nama} juga melanjutkan Website.",
    "18": "Pada pertemuan ini, {nama} mempelajari transisi dan animasi CSS. {nama} juga mempelajari perbedaan antara transisi dan animasi, dan mengimplementasikan reveal on scroll.",
    "19": "Di sesi ini, {nama} belajar membuat website yang responsif - menyesuaikan tampilan agar terlihat bagus di berbagai ukuran layar, dari komputer hingga smartphone.",
    "20": "Pada pertemuan ini, {nama} mempelajari proses development. {nama} juga memilih tipe website yang akan dibuat, dan membuat design website.",
    "21": "Pada pertemuan ini, {nama} mempersiapkan Struktur Project. {nama} juga membuat Header, Footer, dan Home page.",
    "22": "Dalam sesi ini, {nama} membuat halaman Detail dan halaman About - menambahkan konten yang lebih lengkap dan memperkaya struktur website dengan navigasi antar halaman.",
    "23": "Pada pertemuan ini, {nama} membuat Halaman Kontak. Tak hanya itu, {nama} juga membuat Website Lebih Responsif.",
    "24": "Di pertemuan kali ini, {nama} melakukan deploy Situs Web ke Netlify. {nama} juga melakukan presentasi."
  },
  "Android Developer": {
    "1": "Di pertemuan kali ini, {nama} diperkenalkan dengan React Native Framework. {nama} juga menggunakan Component View, Text, dan Button, dan mengatur Tampilan Component.",
    "2": "Pada sesi kali ini, {nama} mempelajari Layout Style. {nama} juga memahami Box Model, mempelajari Text Style, dan mempelajari TouchableOpacity Component.",
    "3": "Pada pertemuan ini, {nama} memahami Flex layout dan Flex Direction. {nama} juga menambahkan Image Component, mempelajari Image Style, dan menambahkan ScrollView Component.",
    "4": "Dalam pertemuan kali ini, {nama} mempelajari ImageBackground & Text Input Component. {nama} juga mempelajari Properti Opacity, mempelajari Props, dan mempelajari Reusable Component.",
    "5": "Pada pertemuan ini, {nama} menambahkan Custom Font. {nama} juga menambahkan Icon, dan membuat Popular Layout.",
    "6": "Di sesi ini, {nama} mengenal Hooks pada React Native. {nama} juga mempelajari  Penggunaan useState dan useEffect, mempelajari setTimeout, dan membuat Project Guess the Country Screen.",
    "7": "Pada pertemuan ini, {nama} mempelajari Stack Navigation. {nama} juga mempelajari Cara Lain Penggunaan useEffect Hook, dan mengenal Properti flexGrow.",
    "8": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya.",
    "9": "Pada pertemuan ini, {nama} mengenal FlatList pada React Native. {nama} juga mempelajari StyleSheet pada React Native, dan membuat Home Screen Movie Collection Project.",
    "10": "Dalam sesi ini, {nama} mempelajari Tentang Horizontal FlatList. {nama} juga menambahkan Component Lain sebelum dan setelah FlatList, dan mengurutkan Data Array of Objects.",
    "11": "Pada pertemuan ini, {nama} mempelajari Mengenai Ternary Operator. {nama} juga menggabungkan StyleSheet dan Inline Style, dan melanjutkan Home Screen Movie Collection Project.",
    "12": "Di pertemuan kali ini, {nama} mempelajari Cara Mengirim Data ke Screen lainnya. {nama} juga mempelajari Cara Menerima Data yang Telah Dikirim, dan membuat Detail Movie Screen.",
    "13": "Pada sesi kali ini, {nama} menampilkan 3 Data Teratas. {nama} juga menampilkan Pesan saat Tidak Ada Data pada FlatList, mempelajari Cara Menambah Kolom pada FlatList, dan membuat Most Viewed Movie Screen.",
    "14": "Pada pertemuan ini, {nama} mempelajari Cara Mengubah Header. Tak hanya itu, {nama} juga membuat Recommended Movie Screen.",
    "15": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya.",
    "16": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya."
  },
  "Python for AI": {
    "1": "Dalam pertemuan kali ini, {nama} mempelajari konsep Artificial Intelligence. {nama} juga mempelajari penerapan AI di kehidupan sehari-hari, mempelajari cakupan AI, dan mempelajari cara kerja Machine Learning.",
    "2": "Pada pertemuan ini, {nama} memahami konsep OOP. {nama} juga membedakan Object, Class, Method, dan Property, mempelajari konsep inheritence di OOP, dan membuat game sederhana menggunakan OOP.",
    "3": "Di sesi ini, {nama} menggunakan Numpy Library. {nama} juga membuat Numpy Array (1D, 2D, 3D) dan memanipulasinya, mempelajari Operasi Dasar pengolahan Numpy Array, dan membuat project TicTacToe menggunakan Numpy.",
    "4": "Pada pertemuan ini, {nama} mempelajari konsep Computer Vision. {nama} juga menggunakan OpenCV Library, mempelajari konsep Image Processing, mempelajari teknik blurring menggunakan OpenCV, dan mempelajari Image Manipulation menggunakan OpenCV.",
    "5": "Pada pertemuan ini, {nama} mempelajari image processing gray scale image di OpenCV. {nama} juga mempelajari konsep Canny Edge Detector dan Countour Detection, mempelajari cara mengidentifikasi warna di OpenCV, dan membuat project Image Cartoonize.",
    "6": "Dalam sesi ini, {nama} menggunakan Pre-trained model dan Machine Learning Framework. {nama} juga membuat aplikasi face detection di gambar, dan membuat aplikasi face detection di video.",
    "7": "Pada pertemuan ini, {nama} mempelajari arsitektur model Single Shot Detector (SSD). {nama} juga dapat membuat project Object Detection menggunakan Model SSD, dan mengimplementasikan project object Detector baik itu di gambar atau di video.",
    "8": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya.",
    "9": "Di pertemuan kali ini, {nama} mempelajari konsep Object Tracking dan cara kerjanya. {nama} juga mempelajari perbedaan Object Detection dan Tracking, mempelajari konsep Euclidean Distance Tracker, mempelajari konsep countour detection, dan mempelajari konsep image thresholding.",
    "10": "Pada sesi kali ini, {nama} mengaplikasikan penggunaan Euclidean Distance Tracker Class. {nama} juga menambahkan Unique Identification dari object yang terdeteksi untuk proses tracking, dan menambahkan \"marker\" untuk object yang sedang di track.",
    "11": "Pada pertemuan ini, {nama} diperkenalkan dengan Mediapipe Library untuk landmark detection. {nama} juga menggunakana Mediapipe untuk Holistic Tracking, mendalami konsep Image Manipulation di Video Frames, dan membuat project Virtual Painter.",
    "12": "Dalam pertemuan kali ini, {nama} mencari posisi landmark tangan menggunakan method enumerate(). {nama} juga mempelajari klasifikasi landmark pada tangan, menginisialisasi mode pada project Virtual Painter (Selection dan Drawing), dan finishing project dengan teknis Video Frame Masking.",
    "13": "Pada pertemuan ini, {nama} mempelajari anatomi Face Mesh di Mediapipe. {nama} juga menggambar landmark menggunakan Face Mesh Landmark model, dan membuat project Pig Face Filter menggunakan Mediapipe.",
    "14": "Di sesi ini, {nama} mempelajari implementasi dari Face Mesh Landmark. {nama} juga mempelajari Facial Area yang ada di dalam Mediapipe, membuat project Face FIlter Dragon Project, dan membuat class Face Mesh untuk mendeteksi Facial Area.",
    "15": "Pada pertemuan ini, {nama} mengidentifikasi apakah mulut terbuka atau tidak. {nama} juga mengidentifikasi nomor landmark pada facial mesh, dan melakukan Video masking untuk menempelkan efek filter ke dalam frames.",
    "16": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya."
  },
  "Python Game Developer": {
    "1": "Di pertemuan kali ini, {nama} mempelajari bagaimana mendevelop game menggunakan Pygame. {nama} juga mempelajari bagaimana cara setting environtment di Pygame, mempelajari bagaimana konsep event controller bekerja, dan mempelajari bagaimana cara menambahkan object di dalam Pygame.",
    "2": "Pada sesi kali ini, {nama} mempelajari bagaimana cara inisialisasi FPS di dalam Pygame. {nama} juga menambahkan object lain ke dalam Pygame canvas, mempelajari bagaimana cara berpindah layout dalam Pygame, mempelajari apa fungsi FPS dalam Game Development, mempelajari list operational dalam Python, dan mempelajari cara menambahkan text ke dalam layout Pygame.",
    "3": "Pada pertemuan ini, {nama} mempelajari functional programming style (modular dan reusable). {nama} juga membuat screen menggunakan function, mempelajari management folder di dalam Pygame, mempelajari bagaimana cara load assets di Pygame, mempelajari bagaimana cara render gambar di Pygame, dan mempelajari cara load dan play sound effect.",
    "4": "Dalam pertemuan kali ini, {nama} mempelajari Gravity Concept dalam game. {nama} juga mempelajari perbedaan Velocity dan Acceleration, dapat menggerakan object secara static, dan menghapus object dari Window.",
    "5": "Pada pertemuan ini, {nama} mempelajari bagaimana cara kerja collide sprite lebih complex. {nama} juga mempelajari kondisi collide dalam game dan dikemas dalam sebuah function, mempelajari bagaimana cara akses global variabel, dan mempelajari bagaimana cara setting high score di dalam Game.",
    "6": "Di sesi ini, {nama} mengenal konsep multiplayer game. {nama} juga mengenal macam-macam fungsi tranform pada Pygame, dan memperdalam terkait function scale dan rotate dalam pygame.",
    "7": "Pada pertemuan ini, {nama} memperdalam mendalami Behavior pygame.Rect() !. {nama} juga mendalami konsep velocity untuk membuat object bergerak, memahami konsep method pygame.key.get_pressed(), dan membuat kode menjadi lebih modular dengan memecar program menjadi beberapa function.",
    "8": "Pada pertemuan ini, {nama} memahami cara membuat custom event or user event di dalam Pygame. {nama} juga memahami bagaimana menerima broadcast user event atau custom event di dalam Pygame, memahami cara membuat winning screen game !, dan mempelajari cara Convert Pygame menjadi executable file.",
    "9": "Dalam sesi ini, {nama} memahami konsep dan terminologi animation secara umum. {nama} juga memahami bagaimana membuat animation sprite di Pygame, menambahkan font external ke dalam Pygame, dan mempelajari function time() lebih lanjut.",
    "10": "Pada pertemuan ini, {nama} mendalami lebih dalam terkait gravitasi dalam game. {nama} juga mengimplementasikan animation frame untuk sprite yang lebih banyak, memahami pengkondisian ketika melakukan spawing object atau enemy, dan menambahkan background sound ke dalam game.",
    "11": "Di pertemuan kali ini, {nama} mengeksplorasi ide untuk project mandiri. {nama} juga mengumpulkan assets untuk project mandiri, membuat timeline development game, dan mempersiapkan folder environtment untuk project.",
    "12": "Pada sesi kali ini, {nama} mengeksplorasi ide untuk project mandiri. {nama} juga mengumpulkan assets untuk project mandiri, membuat timeline development game, dan mempersiapkan folder environtment untuk project.",
    "13": "Pada pertemuan ini, {nama} melanjutkan progress development project. {nama} juga mendesain Screen untuk project mandiri, dan menambahkan sprite ke dalam game.",
    "14": "Dalam pertemuan kali ini, {nama} melanjutkan progress development project. {nama} juga coding Logic untuk Game, membuat sprite bergerak, dan menambahkan enemies untuk game.",
    "15": "Pada pertemuan ini, {nama} mendefinisikan Game Over Condition. {nama} juga melakukan presentasi dan Revisi project, dan finishing project.",
    "16": "Di sesi ini, {nama} melakukan build game menjadi executable file. Tak hanya itu, {nama} juga melakukan publish game tersebut."
  },
  "Python Coder": {
    "1": "Di pertemuan kali ini, {nama} mempelajari Python dan aturan penggunaannya bahasanya. {nama} juga mengenalkan extension untuk mempermudah coding Python, mempelajari cara menampilkan hasil output dengan perintah print, dan mempelajari penulisan operator matematika dalam Python.",
    "2": "Pada sesi kali ini, {nama} mempelajari konsep variable dan cara menggunakannya. {nama} juga mengenalkan perintah input untuk meminta respon dari user, mengenalkan jenis data types dalam python, mengenalkan konsep List dan cara menggunakannya, dan menggambar bentuk menggunakan Python Turtle.",
    "3": "Pada pertemuan ini, {nama} mempelajari konsep data struktur dan tipenya. {nama} juga mempelajari cara mengolah data pada List, Tuple, dan Dictionary, mengenalkan konsep List 2 Dimensi dan cara menggunakannya, dan mempelajari cara memilih data secara acak dengan Random Module.",
    "4": "Dalam pertemuan kali ini, {nama} mempelajari Loops untuk pembuatan coding. {nama} juga mengenalkan jenis dan perbedaan Loops (For, While) serta cara menggunakannya, mengenalkan pentingnya memberikan indentasi dalam penulisan coding, dan mempelajari penggunaan loops untuk mempersingkat penulisan coding.",
    "5": "Pada pertemuan ini, {nama} mempelajari Konsep Conditional dan penggunaan if, elif, dan else untuk membuat kondisi. {nama} juga mengenalkan konsep dan penggunaan operator perbandingan dan logika dalam conditional, mengenalkan konsep case sensitive dengan lower sebagai solusinya, dan mengenalkan konsep conditional loops serta cara penggunaannya dengan While dan If.",
    "6": "Di sesi ini, {nama} mempelajari konsep Function dan Jenis nya. {nama} juga mempelajari cara menggunakan built-in function, dan membuat manual function sendiri untuk fungsi tertentu.",
    "7": "Pada pertemuan ini, {nama} mempelajari konsep penulisan coding one liner. {nama} juga mengenalkan konsep penulisan coding one liner, dan mengenalkan dan menggunakan function parameters dalam program.",
    "8": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya.",
    "9": "Pada pertemuan ini, {nama} diperkenalkan dengan konsep Object-Oriented Programming (OOP) - cara mengorganisir kode menggunakan Class dan Object agar lebih terstruktur dan mudah dikembangkan.",
    "10": "Dalam sesi ini, {nama} diperkenalkan dengan Artificial Intelligence (AI) dan langsung mencoba berbagai penerapannya dalam Python - melihat bagaimana komputer bisa belajar dari data.",
    "11": "Pada pertemuan ini, {nama} mempelajari dan menggunakan TKinter module. Selain itu, {nama} juga mengenalkan dan menggunakan komponen pada TKinter.",
    "12": "Di pertemuan kali ini, {nama} mempelajari Message Boxes, Input Boxes, Labels, dan Buttons. {nama} juga mempelajari cara menggunakan Message Boxes, Input Boxes, Labels, dan Buttons.",
    "13": "Pada sesi kali ini, {nama} belajar menggunakan sistem koordinat pada Canvas di TKinter - memahami bagaimana menentukan posisi dan menggambar bentuk-bentuk geometri di layar.",
    "14": "Pada pertemuan ini, {nama} belajar konsep Events di TKinter - bagaimana program merespons interaksi pengguna seperti klik mouse, penekanan tombol keyboard, dan aksi lainnya.",
    "15": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya.",
    "16": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya."
  }
});
Object.assign(TEMPLATES_EN, {
  "AI Computer Vision": {
    "1": "Today, {nama} learned about Computer Vision - how computers can 'see' and understand images. {nama} used the OpenCV library to explore image processing, blurring, and image editing techniques.",
    "2": "In this session, {nama} learned what a CNN (Convolutional Neural Network) is and how it helps computers recognise images. {nama} was also introduced to TensorFlow, a tool for training AI models.",
    "3": "Today, {nama} learned how to collect datasets for computer vision projects. {nama} used TensorFlow's dataset tools and data augmentation, then built a Horse and Human Classification project.",
    "4": "In this class, {nama} used a pre-trained AI model to build a face detection app - first for photos, then for live video.",
    "5": "Today, {nama} learned about the SSD (Single Shot Detector) model and used it to build an Object Detection app that can identify objects in both images and video.",
    "6": "In this session, {nama} explored the difference between Object Detection and Object Tracking. {nama} also learned about Euclidean Distance Tracker, contour detection, and image thresholding.",
    "7": "Today, {nama} applied the Euclidean Distance Tracker to track moving objects, assigned unique IDs to each detected object, and added visual markers to the tracked items.",
    "8": "{nama} reviewed all previous lessons and completed the mid-term exam.",
    "9": "In this class, {nama} learned about OCR (Optical Character Recognition) and used the EasyOCR library to build an Automatic Number Plate Recognition (ANPR) system.",
    "10": "Today, {nama} explored another use of OCR - recognising handwritten text - and used a pre-trained Keras model along with image processing techniques to make it work.",
    "11": "In this session, {nama} was introduced to MediaPipe, a powerful library for detecting body landmarks. {nama} used it for holistic tracking and built a Virtual Painter project.",
    "12": "Today, {nama} found the exact positions of hand landmarks using the enumerate() method, set up selection and drawing modes in the Virtual Painter, and finished the project using video frame masking.",
    "13": "In this class, {nama} learned about Face Mesh in MediaPipe, drew facial landmarks on a face, and built a fun Pig Face Filter project.",
    "14": "Today, {nama} explored more facial areas in MediaPipe and built a Dragon Face Filter project, including creating a Face Mesh class to detect specific facial regions.",
    "15": "In this session, {nama} learned how to detect whether a mouth is open or closed and used video masking to apply filter effects to each frame in real time.",
    "16": "{nama} reviewed all lessons and completed the final exam for this unit."
  },
  "Python for Data Science": {
    "1": "Today, {nama} was introduced to AI and Python programming. {nama} set up Python, learned the basic syntax, and explored Variables, Data Types, Operators, and Input handling.",
    "2": "In this session, {nama} explored Python Data Structures. {nama} practised with Lists (1D and 2D), Tuples, and built a Password Generator project.",
    "3": "Today, {nama} learned about Dictionaries in Python, how to use and combine different data structures, and built a Movie Dictionary project.",
    "4": "In this class, {nama} was introduced to Loops - For loops and While loops - and practised one-line looping techniques.",
    "5": "Today, {nama} learned about Conditional Statements in Python - how programs make decisions. {nama} combined conditions with loops and built a Jumbled Word game.",
    "6": "In this session, {nama} learned about Functions in Python - both built-in and custom ones. {nama} also built a Discord Chatbot using Discord.py.",
    "7": "Today, {nama} learned about Object-Oriented Programming (OOP) - how to organise code using Classes and Objects - and built a simple game.",
    "8": "{nama} reviewed all previous lessons and completed the mid-term exam.",
    "9": "In this class, {nama} learned about Sorting algorithms - Bubble Sort and Insertion Sort - and how Linear Search works.",
    "10": "Today, {nama} learned how Python Libraries work, used NumPy to create and manipulate arrays, and built a Tic Tac Toe project.",
    "11": "In this session, {nama} explored Data and its types, learned about data collection methods, got started with Google Colab, and practised using Pandas to manage data.",
    "12": "Today, {nama} learned how to define business questions, explored the data analysis process, started an e-commerce data analysis project, and learned how to assess and clean data.",
    "13": "In this class, {nama} practised Exploratory Data Analysis (EDA), applied data grouping techniques, visualised data effectively, and answered business questions from the data.",
    "14": "Today, {nama} explored the relationship between probability and AI, solved basic probability problems using coins and dice, and tackled a Birthday Problem.",
    "15": "{nama} reviewed all previous lessons and completed the final exam.",
    "16": "Today, {nama} completed the final exam."
  },
  "AI Machine Learning": {
    "1": "Today, {nama} learned about the relationship between AI, Machine Learning, and Deep Learning. {nama} also explored how Machine Learning works and practised using Pandas to manage data.",
    "2": "In this session, {nama} learned how Classification works in Machine Learning. {nama} prepared the Iris Flower dataset and visualised it using the Seaborn library.",
    "3": "Today, {nama} learned how the KNN Classifier algorithm works. {nama} trained a model, evaluated it, tuned its settings, and made predictions using the trained model.",
    "4": "In this class, {nama} was introduced to Natural Language Processing (NLP) - how computers understand human language. {nama} explored NLP with ChatGPT and practised using the NLTK library in Python.",
    "5": "Today, {nama} explored the steps involved in Sentiment Analysis and learned about Feature Extraction and Vectorization. {nama} started building a Spotify Review Sentiment Analysis project.",
    "6": "In this session, {nama} learned how Random Forest and Naïve Bayes classifiers work, improved model accuracy, and made predictions using the sentiment analysis model.",
    "7": "Today, {nama} applied NLP to a new project - Fake News Detection. {nama} also compared Classification and Regression models and learned how Logistic Regression works.",
    "8": "{nama} reviewed all previous lessons and completed the mid-term exam.",
    "9": "In this class, {nama} learned about Time Series Forecasting - predicting future values based on past data. {nama} built a Population Prediction project using Linear Regression.",
    "10": "Today, {nama} explored how Sales Forecasting works and built a Sales Prediction project using Plotly for data visualisation and Feature Engineering techniques.",
    "11": "In this session, {nama} learned about Rolling Windows, Exponentially Weighted Moving Average, Logarithmic Transformation, and Neural Networks. {nama} then made predictions using a neural network model.",
    "12": "Today, {nama} was introduced to Unsupervised Learning and K-Means Clustering. {nama} built a Customer Segmentation project using these techniques.",
    "13": "In this class, {nama} learned how Recommender Systems work - both content-based filtering and collaborative filtering - and built a Course Recommendation System.",
    "14": "Today, {nama} learned about Anomaly Detection using the Isolated Forest algorithm and applied it to a Credit Card Fraud Detection project.",
    "15": "{nama} reviewed all lessons and completed the final exam - including a written test and coding exam.",
    "16": "Today, {nama} continued and submitted the coding exam."
  },
  "JavaScript Developer": {
    "1": "Today, {nama} learned what coding is and how it's used in the real world. {nama} was also introduced to JavaScript and the concept of algorithms - step-by-step instructions for solving problems.",
    "2": "In this session, {nama} learned how to spot hoaxes and fake information online. {nama} was also introduced to Variables - a way to store and label information in code - along with different data types.",
    "3": "Today, {nama} learned about Operators in coding - symbols that perform calculations and comparisons. {nama} practised using arithmetic and assignment operators.",
    "4": "In this class, {nama} learned how to handle Cyberbullying and was introduced to Arrays - a way to store multiple items in one place.",
    "5": "Today, {nama} learned how Conditional statements work in coding - how a program can make decisions based on different situations. {nama} practised using comparison and logical operators.",
    "6": "In this session, {nama} explored the idea of a balanced lifestyle. {nama} also learned how to use Switch Statements and Ternary Operators as smarter ways to write conditions.",
    "7": "Today, {nama} learned a structured approach to problem-solving and explored how Loops work in coding - repeating actions automatically.",
    "8": "{nama} reviewed lessons 1–7 and completed the mid-term exam.",
    "9": "In this class, {nama} learned about Nested For Loops - loops inside loops - and Conditional Loops.",
    "10": "Today, {nama} wrote several JavaScript programs to practise what they've learned so far.",
    "11": "In this session, {nama} learned about photo and video manipulation and was introduced to Functions in coding - reusable blocks of code.",
    "12": "Today, {nama} learned about Function Parameters - extra information you can pass into a function to customise its output.",
    "13": "In this class, {nama} learned about copyright and the importance of respecting creative work. {nama} was also introduced to Scope in JavaScript - how variables are accessible in different parts of a program.",
    "14": "Today, {nama} learned how to respond thoughtfully to breaking news. {nama} also explored Return Statements and the forEach loop in JavaScript.",
    "15": "{nama} reviewed lessons 9–14 and completed the exam.",
    "16": "{nama} completed the final exam."
  },
  "Web Developer Teens": {
    "1": "Today, {nama} was introduced to Websites and HTML. {nama} learned how to use Heading, Paragraph, Break, Bold, Italic, and Underline tags.",
    "2": "In this session, {nama} was introduced to CSS - the language used to style websites. {nama} learned about the Box Model, CSS selectors, and used CSS to style the website header.",
    "3": "Today, {nama} learned how Flexbox works for arranging elements on a page, practised placing images effectively, and added product cards to the website.",
    "4": "In this class, {nama} learned about HTML Tables and how to use Colspan and Rowspan attributes to merge cells.",
    "5": "Today, {nama} learned how Lists work in HTML, how to create buttons, and added a pricing table to the website.",
    "6": "In this session, {nama} learned about Hyperlinks and Anchor Links, the difference between Absolute and Relative URLs, and added an About Us page.",
    "7": "Today, {nama} added Font Awesome icons to the website and created a footer with a gradient colour.",
    "8": "In this class, {nama} applied a Google Font, learned the principles of responsive web design, and uploaded the website to the internet.",
    "9": "Today, {nama} was introduced to JavaScript and the HTML DOM. {nama} practised DOM methods and built a Blog page using JavaScript.",
    "10": "In this session, {nama} learned about DOM Events and started building the Blog website project.",
    "11": "Today, {nama} added video and audio elements to the HTML page, embedded external media, and continued building the website.",
    "12": "In this class, {nama} learned how HTML Forms work, explored form elements like Input, Label, Textarea, and Select, and built a form page.",
    "13": "Today, {nama} explored different types of Input fields and Input attributes, then continued building the web form.",
    "14": "In this session, {nama} added CSS styling to the form, set it up to submit data to an email address, and continued the website.",
    "15": "Today, {nama} practised form data submission, built a Modal using HTML, CSS, and JavaScript, and continued the website.",
    "16": "In this class, {nama} built manual and autoplay Image Sliders, practised the forEach method, and completed comprehension check 2.",
    "17": "Today, {nama} explored tools to create Blob shapes, backgrounds, and wave effects, then continued the website.",
    "18": "In this session, {nama} learned about CSS Transitions and Animations, the difference between the two, and added a reveal-on-scroll effect.",
    "19": "Today, {nama} made the website responsive - adjusting its layout to work on different screen sizes.",
    "20": "In this class, {nama} learned about the web development process, chose the type of website to build, and designed the layout.",
    "21": "Today, {nama} set up the project structure and built the Header, Footer, and Home page.",
    "22": "In this session, {nama} built the Detail page and the About page.",
    "23": "Today, {nama} built the Contact page and made the website more responsive.",
    "24": "In this final class, {nama} deployed the website to Netlify and gave a presentation."
  },
  "Android Developer": {
    "1": "Today, {nama} was introduced to React Native - a tool for building mobile apps. {nama} learned about View, Text, and Button components, and how to arrange them on screen.",
    "2": "In this session, {nama} learned how to style app layouts using Layout Style, Box Model, and Text Style, and practised using the TouchableOpacity component.",
    "3": "Today, {nama} learned how to use Flex layout to organise app screens. {nama} also added Image and ScrollView components to their project.",
    "4": "In this class, {nama} explored ImageBackground, Text Input, Opacity, Props, and Reusable Components - tools for building efficient and flexible app layouts.",
    "5": "Today, {nama} added a custom font and icons to their app and built a 'Popular' layout for the interface.",
    "6": "In this session, {nama} was introduced to React Native Hooks. {nama} practised using useState, useEffect, and setTimeout, then built a 'Guess the Country' screen.",
    "7": "Today, {nama} learned about Stack Navigation - moving between screens in a mobile app - and explored another way to use the useEffect Hook.",
    "8": "{nama} reviewed previous lessons and completed the mid-term exam.",
    "9": "In this class, {nama} learned how FlatList and StyleSheet work in React Native. {nama} then built the Home Screen for a Movie Collection app.",
    "10": "Today, {nama} explored Horizontal FlatList, learned how to add components before and after a list, and practised sorting data.",
    "11": "In this session, {nama} learned about the Ternary Operator and how to combine StyleSheet with Inline Style. {nama} continued building the Movie Collection app.",
    "12": "Today, {nama} learned how to send data from one screen to another and how to receive it. {nama} then built the Movie Detail Screen.",
    "13": "In this class, {nama} learned how to display the top 3 results, show an empty state message when there's no data, and add columns to a FlatList. {nama} built the Most Viewed Movie Screen.",
    "14": "Today, {nama} learned how to customise the header in Stack Navigation and built the Recommended Movie Screen.",
    "15": "{nama} completed Part 1 of the Android Apps Development exam.",
    "16": "{nama} completed Part 2 of the Android Apps Development exam."
  },
  "Python for AI": {
    "1": "Today, {nama} was introduced to Artificial Intelligence (AI) - what it is, how it's used in daily life, and how Machine Learning works.",
    "2": "In this session, {nama} learned about Object-Oriented Programming (OOP) - a way to organise code. {nama} learned the difference between Objects, Classes, Methods, and Properties, and built a simple game using OOP.",
    "3": "Today, {nama} used NumPy - a Python library for numbers and data. {nama} created 1D, 2D, and 3D arrays, and built a Tic Tac Toe project using NumPy.",
    "4": "In this class, {nama} was introduced to Computer Vision - how AI can understand images. {nama} used OpenCV for image processing, blurring, and editing.",
    "5": "Today, {nama} learned how to process grayscale images in OpenCV, explored Canny Edge Detection and Contour Detection, learned how to identify colours, and built an Image Cartoonize project.",
    "6": "In this session, {nama} used a pre-trained AI model to build a Face Detection app - for both photos and live video.",
    "7": "Today, {nama} learned about the SSD Object Detection model and used it to identify objects in images and video.",
    "8": "{nama} reviewed all previous lessons and completed the mid-term exam.",
    "9": "In this class, {nama} explored the difference between Object Detection and Object Tracking, and learned about Euclidean Distance Tracker, contour detection, and image thresholding.",
    "10": "Today, {nama} applied the Euclidean Distance Tracker to track objects, assigned unique IDs, and added visual markers.",
    "11": "In this session, {nama} was introduced to MediaPipe for landmark detection, used it for Holistic Tracking, and built a Virtual Painter project.",
    "12": "Today, {nama} found exact hand landmark positions, set up selection and drawing modes, and finished the Virtual Painter project with video masking.",
    "13": "In this class, {nama} explored Face Mesh in MediaPipe, drew facial landmarks, and built a Pig Face Filter.",
    "14": "Today, {nama} learned about different facial regions in MediaPipe and built a Dragon Face Filter project.",
    "15": "In this session, {nama} detected whether a mouth was open or closed, identified facial landmark numbers, and applied filter effects using video masking.",
    "16": "{nama} reviewed all lessons and completed the final exam."
  },
  "Python Game Developer": {
    "1": "Today, {nama} learned how to develop a game using Pygame. {nama} set up the environment, explored the event controller, and added objects to the game window.",
    "2": "In this session, {nama} learned how to set the FPS (Frames Per Second), added more objects to the canvas, practised switching between layouts, and added text to the game.",
    "3": "Today, {nama} learned about functional (modular) programming in Pygame. {nama} built screens using functions, organised folders, loaded assets, rendered images, and added sound effects.",
    "4": "In this class, {nama} learned about Gravity in games - including the difference between Velocity and Acceleration - and practised moving and removing objects from the game window.",
    "5": "Today, {nama} learned how sprite collision works, handled different collision conditions using functions, and added a High Score system to the game.",
    "6": "In this session, {nama} explored multiplayer game concepts and practised using Pygame's transform functions - including scale and rotate.",
    "7": "Today, {nama} deepened their understanding of pygame.Rect(), explored velocity for moving objects, practised pygame.key.get_pressed(), and split the program into smaller functions for cleaner code.",
    "8": "In this class, {nama} learned how to create custom events in Pygame, received broadcast events, built a winning screen, and converted the game into an executable file.",
    "9": "Today, {nama} learned about animation concepts, built animated sprites in Pygame, added an external font, and explored the time() function further.",
    "10": "In this session, {nama} deepened their understanding of gravity in games, added more animation frames for sprites, handled spawning conditions for enemies, and added background music.",
    "11": "Today, {nama} explored ideas for their personal game project, collected assets, created a development timeline, and set up the project folder.",
    "12": "In this class, {nama} continued exploring and refining the game concept, collected more assets, and prepared the project environment.",
    "13": "Today, {nama} continued developing the project - designed the game screens and added sprites.",
    "14": "In this session, {nama} wrote the game logic, made sprites move, and added enemies.",
    "15": "Today, {nama} defined the Game Over condition, presented and revised the project, and completed it.",
    "16": "In this final class, {nama} built the game into an executable file and published it."
  },
  "Python Coder": {
    "1": "Today, {nama} was introduced to Python - a popular programming language. {nama} learned Python's basic rules, installed a helpful coding extension, learned how to print output, and practised writing maths operations in code.",
    "2": "In this session, {nama} learned about Variables, how to get input from a user, the different data types in Python, how Lists work, and drew shapes using Python Turtle.",
    "3": "Today, {nama} explored Data Structures - different ways to organise information. {nama} practised working with Lists, Tuples, and Dictionaries, and learned how to pick random data using the Random module.",
    "4": "In this class, {nama} was introduced to Loops in Python - For loops and While loops. {nama} learned why indentation matters in coding and how loops save time by repeating code efficiently.",
    "5": "Today, {nama} learned about Conditional Statements using if, elif, and else. {nama} also practised comparison and logical operators, learned about case sensitivity, and built Conditional Loops using While and If.",
    "6": "In this session, {nama} was introduced to Functions in Python - both built-in ones and custom ones created from scratch.",
    "7": "Today, {nama} learned One-Liner coding - writing compact, efficient code - and practised using Function Parameters.",
    "8": "{nama} reviewed previous lessons and completed the Python Coder mid-term exam.",
    "9": "In this class, {nama} was introduced to Object-Oriented Programming (OOP) - a way of organising code around objects and classes.",
    "10": "Today, {nama} was introduced to Python Modules and got a first look at Artificial Intelligence.",
    "11": "In this session, {nama} was introduced to TKinter - a Python library for building apps with windows and buttons. {nama} explored its basic components.",
    "12": "Today, {nama} learned how to use Message Boxes, Input Boxes, Labels, and Buttons in TKinter to build interactive app windows.",
    "13": "In this class, {nama} learned how to use coordinates on a TKinter Canvas to draw and position things accurately.",
    "14": "Today, {nama} explored Mouse Events in TKinter - how an app can respond when the user clicks or moves the mouse.",
    "15": "{nama} reviewed previous lessons and completed Part 1 of the Python Coder Final Exam.",
    "16": "{nama} completed Part 2 of the Python Coder Final Exam."
  }
});
