// ============================================================
// TEMPLATES / TEMPLATES_EN slice — criteria: Kids
// ============================================================
// Bagian dari performance split (rencana-10-10-non-security.md bagian 5.1).
// Sama seperti data.kids.js — dimuat DINAMIS oleh js/lazy-loader.js,
// bukan di <head>. JANGAN declare ulang 'const TEMPLATES'/'TEMPLATES_EN'
// di sini — js/templates.js (file inti) sudah mendeklarasikan keduanya
// sebagai objek kosong.
// ============================================================

Object.assign(TEMPLATES, {
  "Coding Explorer": {
    "1": "Dalam pertemuan kali ini, {nama} mengenal Coding sebagai Bahasa Komputer. Di samping itu, {nama} juga menyusun Coding sesuai Algoritma yang Benar.",
    "2": "Pada pertemuan ini, {nama} memahami pengaruh Screen Time dan Gadget Addiction. {nama} juga belajar menggunakan Event dan Loop dalam Coding.",
    "3": "Di sesi ini, {nama} mempelajari cara mencegah dan mengatasi Cyber Bullying. Tidak hanya itu, {nama} juga menggunakan Scratch untuk membuat game sederhana.",
    "4": "Pada pertemuan ini, {nama} mempelajari cara Penggunaan dan Perawatan Gadget dengan benar. {nama} juga mengenal konsep Conditional dan penerapannya dalam Coding.",
    "5": "Pada pertemuan ini, {nama} diperkenalkan dengan teknologi Virtual Reality (VR) - sebuah teknologi yang menciptakan lingkungan digital yang terasa nyata. {nama} mempelajari apa itu VR, cara kerjanya, dan langsung mencoba pengalaman VR.",
    "6": "Dalam sesi ini, {nama} mempelajari apa itu Mindfull Message. Selain itu, {nama} juga mengenal dan mengendalikan Drone secara virtual.",
    "7": "Pada pertemuan ini, {nama} memahami arti Bug pada program. {nama} juga mengenal Glide pada Scratch dan penerapan pada game.",
    "8": "Di pertemuan kali ini, {nama} melakukan review seluruh materi dari pertemuan 1 hingga 7 dan mengikuti Ujian Coding Explorer Level 1.",
    "9": "Pada sesi kali ini, {nama} mempelajari pentingnya Tetap Berusaha dan Pantang Menyerah. {nama} juga mengenal Conditional Loop dalam Coding, dan micro:bit Truth or Dare Game.",
    "10": "Pada pertemuan ini, {nama} mengenal Spam dan Cara Menghindarinya. {nama} juga mempelajari algoritma dalam Memecahkan Masalah, dan menggunakan Kode Forever dalam Coding.",
    "11": "Dalam pertemuan kali ini, {nama} mengenal virus komputer dan cara mengatasinya. Lebih dari itu, {nama} juga membuat aquarium dengan AR Cube.",
    "12": "Pada pertemuan ini, {nama} membuat sebuah flying game menggunakan Scratch - menggabungkan semua konsep yang telah dipelajari sebelumnya untuk menciptakan game yang lengkap.",
    "13": "Di sesi ini, {nama} mempelajari perkembangan teknologi dalam kehidupan manusia. {nama} juga mengenal Variable dalam Coding.",
    "14": "Pada pertemuan ini, {nama} belajar menggunakan Function di dalam lingkungan Virtual Reality - menulis kode untuk memicu aksi dan animasi di dunia virtual.",
    "15": "Pada pertemuan ini, {nama} mengenal Artificial Intelligence. Di samping itu, {nama} juga mengenal Text Coding dan Bahasa Pemrograman Python.",
    "16": "Dalam sesi ini, {nama} melakukan review materi sebelumnya dan mengikuti Ujian Coding Explorer Level 2.",
    "17": "Pada pertemuan ini, {nama} mengenal media balance. {nama} juga membuat game dengan konsep broadcast dan clone.",
    "18": "Di pertemuan kali ini, {nama} mempelajari internet of Things untuk membantu kehidupan. Tak hanya itu, {nama} juga mengenal List dalam Coding.",
    "19": "Pada sesi kali ini, {nama} menggunakan Scratch untuk membuat Soccer Game - coding gerakan pemain, fisika bola, dan sistem skor.",
    "20": "Pada pertemuan ini, {nama} mengenal konsep Additive design. {nama} juga membuat game Create Own World - Part 1.",
    "21": "Dalam pertemuan kali ini, {nama} membuat Game Sendiri. Selain itu, {nama} juga menentukan Ide dan Mengumpulkan Aset Game.",
    "22": "Pada pertemuan ini, {nama} membuat Game Sendiri. {nama} juga menyusun Game Layout, Coding Start Layout, dan Coding Main Game.",
    "23": "Di sesi ini, {nama} membuat Game Sendiri. Tak hanya itu, {nama} juga menambahkan life, score, next level, dan game over pada game.",
    "24": "Pada pertemuan ini, {nama} membuat Game Sendiri. Di samping itu, {nama} juga melakukan presentasi Game, Feedback, Debugging dan Share Game.",
    "25": "Pada pertemuan ini, {nama} mempelajari Mobile Apps. {nama} juga mendapatkan pengenalan tentang MIT App Inventor.",
    "26": "Dalam sesi ini, {nama} membuat Clicker App. Tidak hanya itu, {nama} juga membuat Timer App.",
    "27": "Pada pertemuan ini, {nama} mempelajari Translator APP. {nama} juga menggunakan Spinner dan Speech Recognizer dalam Translator App.",
    "28": "Di pertemuan kali ini, {nama} membuat aplikasi kalkulator. Selain itu, {nama} juga membuat My Walk App dengan pedometer.",
    "29": "Pada sesi kali ini, {nama} membuat aplikasi menggambar. {nama} juga membuat game Tic tac Toe.",
    "30": "Pada pertemuan ini, {nama} mengeksplorasi ide aplikasi buatanmu. Lebih dari itu, {nama} juga menyiapkan assets.",
    "31": "Dalam pertemuan kali ini, {nama} membuat aplikasi sesuai tema yang telah dipilih - menggabungkan semua elemen desain dan coding menjadi app yang siap digunakan.",
    "32": "Pada pertemuan ini, {nama} meluncurkan aplikasi buatannya sendiri dan mempresentasikannya kepada teman-teman sekelas."
  },
  "Tech Explorer": {
    "1": "Pada pertemuan ini, {nama} memahami Kecanduan Game Loop. {nama} juga memahami Coding sebagai Bahasa Komputer, dan Menyusun Kode dengan Algoritma yang Tepat.",
    "2": "Dalam sesi ini, {nama} memahami Konsep Probabilitas (RNG) dalam Permainan. Selain itu, {nama} juga memahami Konsep Event sebagai Pemicu dalam Coding, dan membuat Blok Code Berdasarkan Event dan Tindakan.",
    "3": "Di pertemuan kali ini, {nama} memahami Strategi Top Up Game yang Tepat. Di samping itu, {nama} juga memahami Virtual Reality.",
    "4": "Pada sesi kali ini, {nama} memahami konsep scrolling tanpa batas dan cara mengatasinya. Tak hanya itu, {nama} juga mampu mendesain bagian Merge Cube dalam AR, mampu membuat kuis untuk objek di DelightEx edu, dan mampu mengunggah video dan menampilkannya di Merge Cube.",
    "5": "Dalam pertemuan kali ini, {nama} memahami Bahaya Buble Information. Lebih dari itu, {nama} juga mempelajari Konsep Loop dalam Osmo Coding.",
    "6": "Pada pertemuan ini, {nama} mencegah FOMO Selama Event Game Online. Tidak hanya itu, {nama} juga membuat Proyek VR yang Lebih Canggih.",
    "7": "Dalam sesi ini, {nama} mampu memahami konsep login harian dalam permainan video serta cara menghindari kecanduan permainan video. {nama} juga memahami konsep desain rumah sederhana, memahami Konsep Warna dalam Desain 3D, dan Menambahkan animasi dan teks ke Delightex Edu.",
    "8": "{nama} melaksanakan sesi review materi 1-7 dan mengikuti ujian Level Xplorer 1 pada pertemuan ini.",
    "9": "Pada sesi kali ini, {nama} mengidentifikasi Bahaya \"Stranger Danger\" di Dunia Maya. Di samping itu, {nama} juga mengoperasikan Antarmuka Dasar Scratch, dan Mengimplementasikan Kode Event dan Loop pada Animasi.",
    "10": "Dalam pertemuan kali ini, {nama} memahami Definisi dari Block Coding Motion pada Scratch. Tak hanya itu, {nama} juga mengidentifikasi Block Coding Motion yang Tersedia di Scratch, mengidentifikasi Kapan Harus Menggunakan Block Coding Motion pada Scratch, dan membuat Project pada Scratch Menggunakan Block Coding Motion.",
    "11": "Pada pertemuan ini, {nama} mengenal Block Coding yang Ada pada Tab Looks pada Scratch. Lebih dari itu, {nama} juga mengidentifikasi Kegunaan Setiap Block Coding pada Tab Looks, mengidentifikasi Kondisi Kapan Block Coding pada Tab Looks Digunakan, dan menerapkan Block Coding pada Tab Looks dalam Contoh Proyek Sederhana.",
    "12": "Dalam sesi ini, {nama} memahami Apa Definisi Dari Block Coding Sound pada Scratch. Tidak hanya itu, {nama} juga Dapat Mengidentifikasi Block Coding Sound yang Tersedia di Scratch, Dapat Mengidentifikasi Kapan Harus Menggunakan Block Coding Sound pada Scratch, dan mampu Membuat Project pada Scratch Menggunakan Block Coding Motion, serta mampu Melakukan Editing Sound pada Scratch.",
    "13": "Di pertemuan kali ini, {nama} menganalisis Keamanan Digital Melalui QR Code. {nama} juga memahami Struktur Blok Event pada Scratch, dan menguasai Logika Komunikasi Antar-Karakter (Broadcast).",
    "14": "Pada sesi kali ini, {nama} memahami Manfaat dan Keamanan Cloud Storage. Selain itu, {nama} juga menguasai Logika Perulangan (Looping Control), dan menerapkan Percabangan Kondisional (Conditional Logic).",
    "15": "Dalam pertemuan kali ini, {nama} memahami Konsep dari Search Engine. Di samping itu, {nama} juga memahami Apa Definisi Dari Block Coding Sensing pada Scratch, Dapat Mengidentifikasi Block Coding Sensing yang Tersedia di Scratch, dan Dapat Mengidentifikasi Kapan Harus Menggunakan Block Coding Sensing pada Scratch, serta mampu Membuat Project pada Scratch Menggunakan Block Coding Sensing.",
    "16": "{nama} melaksanakan sesi review materi 9-15 serta mengikuti ujian tertulis dan coding pada pertemuan ini.",
    "17": "Dalam sesi ini, {nama} mampu Membuat Password yang Kuat. Lebih dari itu, {nama} juga memahami Apa Definisi dari Block Coding Operator pada Scratch, Dapat Mengidentifikasi Block Coding Operator yang Tersedia di Scratch, dan Dapat Mengidentifikasi Kapan Harus Menggunakan Block Coding Operator pada Scratch, serta mampu Membuat Project pada Scratch Menggunakan Block Coding Operator.",
    "18": "Di pertemuan kali ini, {nama} memahami Konsep Deepfake. Tidak hanya itu, {nama} juga memahami Apa Definisi dari Block Coding Variable pada Scratch, Dapat Mengidentifikasi Block Coding Variable yang Tersedia di Scratch, dan Dapat Mengidentifikasi Kapan Harus Menggunakan Block Coding Variable pada Scratch, mampu Membuat Project pada Scratch Menggunakan Block Coding Variable, serta pengenalan Variable dan List.",
    "19": "Pada sesi kali ini, {nama} memahami Konsep Otomasi dalam Kehidupan Sehari-hari. {nama} juga mengenal Konsep Function dalam Coding, dan mengenal Block Coding My Blocks Pada Scratch.",
    "20": "Dalam pertemuan kali ini, {nama} memahami Dasar Teknologi Generative AI. Selain itu, {nama} juga menguasai Teknik Prompting yang Efektif, menerapkan Etika dan Kejujuran dalam Karya AI, dan mengintegrasikan AI Buddy ke dalam Lingkungan VR Edu Delightex.",
    "21": "Pada pertemuan ini, {nama} memahami Apa Fungsi Slide Presentasi. Di samping itu, {nama} juga memahami Cara Mendapatkan Ide Project Game, dan mengumpulkan Asset Project Game Baik dari Internet Maupun AI.",
    "22": "Dalam sesi ini, {nama} memahami Teknologi di Balik AI Voice. Tak hanya itu, {nama} juga mengintegrasikan Aset Audio ke dalam Desain Proyek Digital, dan melanjutkan Proses Desain dari Asset Game yang Telah Dikumpulkan.",
    "23": "Di pertemuan kali ini, {nama} menanggapi Konsep Kepemilikian pada Seni AI. Lebih dari itu, {nama} juga menyelesaikan Tahap Coding pada Project Final, dan mengerti Apa Saja yang Harus Dilakukan Saat Coding Project Final.",
    "24": "Pada pertemuan ini, {nama} memahami poin penting dalam presentasi. Selain itu, {nama} juga mengerjakan ujian tertulis dengan seksama dan mempresentasikan project dengan baik."
  },
  "Game Developer": {
    "1": "Pada pertemuan ini, {nama} mengenal website Construct 3. Tak hanya itu, {nama} juga menggunakan behavior untuk menggerakkan sprite.",
    "2": "Dalam sesi ini, {nama} menyusun Maze. Di samping itu, {nama} juga menggunakan Event Sheet.",
    "3": "Pada pertemuan ini, {nama} mengenal Animation Frame. {nama} juga belajar menggunakan behavior 8 Direction dan Bound to Layout.",
    "4": "Di pertemuan kali ini, {nama} menambahkan enemy dan score. Tidak hanya itu, {nama} juga membuat next level pada game.",
    "5": "Pada sesi kali ini, {nama} mengarahkan sprite mengikuti mouse pointer. {nama} juga mempelajari behaviour physics.",
    "6": "Pada pertemuan ini, {nama} menambahkan Particles Effect. Selain itu, {nama} juga menambahkan Level 2 pada game.",
    "7": "Dalam pertemuan kali ini, {nama} melakukan review seluruh materi dari pertemuan 1 hingga 6 sebagai persiapan ujian.",
    "8": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya.",
    "9": "Pada pertemuan ini, {nama} menggerakkan paddle dan memantulkan bola. {nama} juga menyusun blocks & menambahkan instance variable.",
    "10": "Di sesi ini, {nama} menambahkan Variable dan Respawn Ball. Lebih dari itu, {nama} juga menambahkan level pada game.",
    "11": "Pada pertemuan ini, {nama} menambahkan Start, Win, dan Game Over Layout. {nama} juga menambahkan Start dan Replay Button.",
    "12": "Pada pertemuan ini, {nama} membuat srolling background dan menggerakkan player. Di samping itu, {nama} juga memilih player yang akan dimainkan dan rancom costume obstacles.",
    "13": "Dalam sesi ini, {nama} menggunakan Sprite font untuk Score dan Life. {nama} juga menggunakan Family Features pada Construct.",
    "14": "Pada pertemuan ini, {nama} menambahkan enemy dengan instance variable. Tak hanya itu, {nama} juga menambahkan efek Stardust dengan Particles.",
    "15": "Di pertemuan kali ini, {nama} melakukan review materi dari pertemuan sebelumnya sebagai persiapan ujian Game Developer.",
    "16": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya.",
    "17": "Pada sesi kali ini, {nama} membuat desain layout dengan Tilemap. {nama} juga menggerakkan player pada game platformer.",
    "18": "Pada pertemuan ini, {nama} menambahkan obstacles dan enemy pada Game. Selain itu, {nama} juga menambahkan item pada Game.",
    "19": "Dalam pertemuan kali ini, {nama} menambahkan Next Level. {nama} juga membuat Item Menempel Pada Player.",
    "20": "Pada pertemuan ini, {nama} menambahkan AI Enemy. Tak hanya itu, {nama} juga mengupload Game ke Website.",
    "21": "Di sesi ini, {nama} mengeksplorasi ide game. Di samping itu, {nama} juga mengumpulkan asset.",
    "22": "Pada pertemuan ini, {nama} merencanakan game buatannya sendiri dan menyusun layout secara lengkap - mengatur scene, background, dan elemen-elemen utama yang siap untuk di-coding.",
    "23": "Pada pertemuan ini, {nama} melakukan finishing dan Debugging. {nama} juga melakukan persiapan Launch.",
    "24": "Dalam sesi ini, {nama} melakukan launch Game. Tidak hanya itu, {nama} juga melakukan presentasi."
  },
  "Code and Design with Roblox": {
    "1": "Pada pertemuan ini, {nama} memahami perangkat yang digunakan untuk komputer. {nama} juga mendapatkan pengenalan tentang roblox, literasi game, dan mempersiapkan roblox studio.",
    "2": "Di pertemuan kali ini, {nama} memahami menu dan shortcut di roblox studio. {nama} juga mendapatkan pengenalan tentang modeling, dan membuat sebuah model rumah.",
    "3": "Pada sesi kali ini, {nama} memahami tools modelling. {nama} juga membuat sebuah model menggunakan referensi google image, memahami tentang anchor, dan memahami save to roblox dan collaborate.",
    "4": "Pada pertemuan ini, {nama} memahami konsep parent & children. {nama} juga memahami kegunaan toolbox, membuat sebuah efek, dan menyelesaikan project rumah.",
    "5": "Dalam pertemuan kali ini, {nama} merancang latar belakang map. {nama} juga memahami tool terrain editor, dan membuat project baru.",
    "6": "Pada pertemuan ini, {nama} memahami smooth dan flatten. {nama} juga menggunakan plugin brush tool.",
    "7": "Di sesi ini, {nama} memahami copyright. Selain itu, {nama} juga memahami cara Publish project.",
    "8": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya.",
    "9": "Pada pertemuan ini, {nama} memahami rings of responsibility. {nama} juga memahami generate tool di terrain editor, dan membuat game underwater.",
    "10": "Pada pertemuan ini, {nama} memahami tool solid modeling. {nama} juga membuat rumah underwater, dan memahami gravitasi di roblox.",
    "11": "Dalam sesi ini, {nama} memahami tentang screen time. {nama} juga memahami tentang scripting, memahami properties, dan membuat script untuk part.",
    "12": "Pada pertemuan ini, {nama} menambahkan papan yang berisi tulisan. {nama} juga menambahkan suara, dan mengubah atmosphere.",
    "13": "Di pertemuan kali ini, {nama} memahami cyber bullying. {nama} juga memahami konsep variable dan jenisnya, memahami konsep Instance.new(), dan memahami kode wait().",
    "14": "Pada sesi kali ini, {nama} memahami konsep loop dan while loop. {nama} juga menggunakan while loop, dan menambahkan script untuk menggerakan object.",
    "15": "Pada pertemuan ini, {nama} mengenal animasi. {nama} juga memahami tools untuk membuat Animasi, dan membuat sebuah animasi untuk Farmland.",
    "16": "Dalam pertemuan kali ini, {nama} melakukan review materi meeting 9 - 15. {nama} juga mengerjakan roblox explorer 2 exam.",
    "17": "Pada pertemuan ini, {nama} memahami fungsi dari image label. {nama} juga menggunakan image label pada part, dan membuat nama meja.",
    "18": "Di sesi ini, {nama} memahami fungsi dari trap. {nama} juga membuat laser dengan beam effect untuk trap, dan membuat trap pada pintu menuju kitchen.",
    "19": "Pada pertemuan ini, {nama} mengeksplorasi bangunan dan model. {nama} juga memahami aturan dan etika membuat project, membuat draft ide bangunan, dan memulai modeling bangunan.",
    "20": "Pada pertemuan ini, {nama} memahami kombinasi warna. {nama} juga mempelajari tips untuk modelling, dan melanjutkan modelling bangunan.",
    "21": "Dalam sesi ini, {nama} menambahkan detail pada object. Lebih dari itu, {nama} juga menyelesaikan modelling bangunan.",
    "22": "Pada pertemuan ini, {nama} memahami Interactive parts. {nama} juga menambahkan scripts kedalam game.",
    "23": "Di pertemuan kali ini, {nama} membuat presentasi tentang project Roblox yang telah dibuat - menyiapkan materi dan berlatih menyampaikannya kepada orang lain.",
    "24": "Pada sesi kali ini, {nama} mempresentasikan hasil project Roblox kepada teman-teman sekelas dan menerima feedback."
  },
  "Interactive Mechanics on Roblox": {
    "1": "Pada pertemuan ini, {nama} membuat desain map. {nama} juga membuat lingkungan theme park, dan mengubah atmosphere map theme park.",
    "2": "Dalam pertemuan kali ini, {nama} membuat model interaktif. {nama} juga memahami event dalam coding, dan membuat script untuk komedi putar.",
    "3": "Pada pertemuan ini, {nama} diperkenalkan dengan photopea. {nama} juga membuat desain baju sederhana, mengimport desain ke asset manager, dan coding untuk menggunakan baju pada game.",
    "4": "Di sesi ini, {nama} membuat storyline. {nama} juga mempersiapkan clue pada game, dan modelling bangunan.",
    "5": "Pada pertemuan ini, {nama} melakukan modelling kunci. {nama} juga memahami konsep conditional statement, dan coding kunci dan pintu.",
    "6": "Pada pertemuan ini, {nama} melakukan modelling clue. {nama} juga coding show text label, dan menambahkan lightswitch.",
    "7": "Dalam sesi ini, {nama} melakukan konfigurasi atmosphere. {nama} juga melakukan modeling headlamp, dan publish serta bermain bersama.",
    "8": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya.",
    "9": "Pada pertemuan ini, {nama} diperkenalkan dengan to blender. {nama} juga mempelajari basic controls of blender, dan create your first model.",
    "10": "Di pertemuan kali ini, {nama} membuat model botol. {nama} juga melakukan modeling aksesori player, dan export object ke roblox studio.",
    "11": "Pada sesi kali ini, {nama} melakukan import object pada project. {nama} juga mengenal tentang screen gui, mendesign screen gui, dan menggunakan tween service.",
    "12": "Pada pertemuan ini, {nama} merencanakan game. {nama} juga melakukan modeling map dan bangunan, dan menambahkan lukisan dengan image label.",
    "13": "Dalam pertemuan kali ini, {nama} melanjutkan modeling bangunan dan interior. {nama} juga menentukan lokasi objek yang akan disembunyikan, dan menambahkan screen gui untuk clue.",
    "14": "Pada pertemuan ini, {nama} membuat model low poly: barrel. Di samping itu, {nama} juga membuat model untuk object utama Finding Game.",
    "15": "Di sesi ini, {nama} melakukan export dan importing banyak parts dari blender. {nama} juga membuat gui yang muncul saat menemukan objek, dan menambahkan coding untuk mengambil objek.",
    "16": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya.",
    "17": "Pada pertemuan ini, {nama} memahami places dan fungsinya. {nama} juga menggabungkan game sebelumnya ke lobby, dan membuat gambar untuk badges dan game pass.",
    "18": "Pada pertemuan ini, {nama} memahami struktur thumbnail dan game icon. {nama} juga membuat tombol return, dan membuat opening GUI.",
    "19": "Dalam sesi ini, {nama} merencanakan game yang akan dibuat. {nama} juga menambahkan place baru kedalam project lobby, dan memulai modelling game.",
    "20": "Pada pertemuan ini, {nama} melanjutkan modelling. {nama} juga menggunakan blender untuk modelling.",
    "21": "Di pertemuan kali ini, {nama} menambahkan GUI. Tak hanya itu, {nama} juga menambahkan tween animation.",
    "22": "Pada sesi kali ini, {nama} menambahkan kode untuk misi. {nama} juga menambahkan script teleport dengan event touch.",
    "23": "Pada pertemuan ini, {nama} membuat presentasi project. Selain itu, {nama} juga membuat thumbnail.",
    "24": "Dalam pertemuan kali ini, {nama} mempresentasikan project game yang telah selesai kepada teman-teman sekelas dan menerima feedback."
  },
  "Full Stack Programming on Roblox": {
    "1": "Di sesi ini, {nama} mengenal roblox game. {nama} juga mengenal interface pada roblox studio, memahami proses modelling, dan membuat obby game.",
    "2": "Pada pertemuan ini, {nama} memahami pengertian coding. {nama} juga mempelajari konsep variable, mempelajari konsep properti, dan mempelajari konsep reusing code.",
    "3": "Pada pertemuan ini, {nama} mempelajari proses modeling. {nama} juga mempelajari tool effect.",
    "4": "Dalam sesi ini, {nama} mengenal adventure game. {nama} juga mengenal terrain editor dan penerapannya, dan membuat terrain dan model sell platform.",
    "5": "Pada pertemuan ini, {nama} mempelajari leaderboard. Di samping itu, {nama} juga mempelajari konsep function.",
    "6": "Di pertemuan kali ini, {nama} mempelajari cara kerja harvestable item. {nama} juga memahami konsep conditional statement.",
    "7": "Pada sesi kali ini, {nama} memahami cara kerja sell platform - tempat pemain menukar item yang mereka kumpulkan dengan mata uang di dalam game.",
    "8": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya.",
    "9": "Pada pertemuan ini, {nama} mampu membuat karakter player sendiri. Tak hanya itu, {nama} juga memahami cara menggerakkan custom player.",
    "10": "Dalam pertemuan kali ini, {nama} mempelajari konsep event. {nama} juga membuat model bullet.",
    "11": "Pada pertemuan ini, {nama} membuat kode untuk men-spawn bullet di dalam game. {nama} memahami bagaimana sistem tembakan bekerja dan berhasil menerapkannya ke karakter pemain.",
    "12": "Di sesi ini, {nama} memahami alur story game. {nama} juga memahami dan menerapkan screen gui, dan memahami dan menerapkan remote event.",
    "13": "Pada pertemuan ini, {nama} memahami pengertian module script. Selain itu, {nama} juga mempelajari pembuatan screen gui yang dinamis.",
    "14": "Pada pertemuan ini, {nama} mengenal pengertian animasi. {nama} juga mempelajari cara membuat animasi di roblox, dan menerapkan animasi pada story game.",
    "15": "Dalam sesi ini, {nama} mempelajari click detector. {nama} juga memahami alur task 2, dan menerapkan efect di task 3.",
    "16": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya.",
    "17": "Pada pertemuan ini, {nama} mengeksplorasi ide game. {nama} juga membuat rencana game yang akan dibuat, dan mulai membuat desain model dan lingkungan game.",
    "18": "Di pertemuan kali ini, {nama} melanjutkan pembangunan dan penyempurnaan model game - mengerjakan tata letak map, props, dan lingkungan game agar dunia game terasa hidup.",
    "19": "Pada sesi kali ini, {nama} mulai menulis kode utama untuk game buatannya sendiri - menyiapkan variabel, menulis skrip untuk mekanik utama, dan membangun fondasi logika game.",
    "20": "Pada pertemuan ini, {nama} melanjutkan penulisan dan pengujian kode game - men-debug masalah, menyempurnakan mekanik, dan memastikan semua fitur berjalan dengan benar.",
    "21": "Dalam pertemuan kali ini, {nama} menyelesaikan seluruh proses coding game - menyempurnakan logika, memperbaiki bug terakhir, dan memastikan pengalaman bermain berjalan dengan mulus.",
    "22": "Pada pertemuan ini, {nama} menunjukkan progress game ke teman sekelas. {nama} juga memberi dan menerima feedbacks dari teman sekelas dan guru.",
    "23": "Di sesi ini, {nama} belajar bagaimana pemain bisa mendapatkan Robux dari game yang mereka buat sendiri, termasuk memahami sistem monetisasi di Roblox.",
    "24": "Pada pertemuan ini, {nama} mempresentasikan game yang telah selesai kepada teman-teman sekelas."
  },
  "Advanced Lua Programming on Roblox": {
    "1": "Pada sesi kali ini, {nama} memahami game development pada battle royale game. {nama} juga mempersiapkan map, mempelajari multiplayer game loop, dan menambahkan chest yang bisa terbuka.",
    "2": "Pada pertemuan ini, {nama} mempelajari lobby system. {nama} juga mempelajari konsep table & for loop in pairs, dan membuat teleport system.",
    "3": "Dalam pertemuan kali ini, {nama} membuat model sword. {nama} juga membuat coding untuk sword.",
    "4": "Pada pertemuan ini, {nama} menambahkan health potion. Selain itu, {nama} juga menambahkan gun player.",
    "5": "Di sesi ini, {nama} menerapkan timer module. {nama} juga membuat screen gui yang dinamis.",
    "6": "Pada pertemuan ini, {nama} memahami proses pengembalian player kalah ke lobby. Lebih dari itu, {nama} juga memahami cara mengakhiri match.",
    "7": "Pada pertemuan ini, {nama} memahami proses kembali ke intermission setelah match selesai. {nama} juga mempelajari bagaimana sistem game membersihkan dan me-reset state sebelum babak berikutnya dimulai.",
    "8": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya.",
    "9": "Dalam sesi ini, {nama} mempelajari alur game cleaner boat simulator. {nama} juga memahami proses persiapan materials.",
    "10": "Pada pertemuan ini, {nama} membuat screen GUI yang digunakan pemain untuk memilih dan menyusun bagian-bagian boat. {nama} memahami cara kerja tampilan interaktif ini di dalam game Cleaner Boat Simulator.",
    "11": "Di pertemuan kali ini, {nama} memahami cara kerja placement system yang memungkinkan pemain menempatkan objek di dalam game. {nama} mempelajari logika di balik sistem ini dan bagaimana menerapkannya dalam proyek.",
    "12": "Pada sesi kali ini, {nama} melakukan coding untuk launch boat. Di samping itu, {nama} juga coding untuk remove material boat.",
    "13": "Pada pertemuan ini, {nama} mempelajari cara kerja collecting trash dengan boat. {nama} juga mampu menampilkan jumlah sampah di screen gui.",
    "14": "Dalam pertemuan kali ini, {nama} mempelajari cara menonaktifkan materials dari screen gui. Tak hanya itu, {nama} juga mampu membuat desain quiz gui.",
    "15": "Pada pertemuan ini, {nama} mampu membuat quiz untuk upgrade boat. {nama} juga memahami proses upgrade boat.",
    "16": "{nama} melaksanakan sesi review dan ujian pada pertemuan ini sebagai evaluasi pemahaman materi yang telah dipelajari sebelumnya.",
    "17": "Di sesi ini, {nama} menampilkan soal matematika di layar dalam game Math Obby. {nama} memahami cara mengambil soal secara dinamis dan menampilkannya melalui screen GUI.",
    "18": "Pada pertemuan ini, {nama} memahami cara menampilkan pilihan jawaban. Selain itu, {nama} juga memahami cara memeriksa jawaban player.",
    "19": "Pada pertemuan ini, {nama} mengeksplorasi ide game. {nama} juga membuat rencana game yang akan dibuat, dan mulai membuat lingkungan dan model.",
    "20": "Dalam sesi ini, {nama} melanjutkan pengerjaan model game - menyempurnakan desain, menambahkan detail, dan memastikan tampilan keseluruhan sudah rapi dan konsisten.",
    "21": "Pada pertemuan ini, {nama} mulai menulis kode utama untuk game - menyiapkan logika game, variabel, dan fungsi-fungsi penting yang diperlukan agar game bisa berjalan.",
    "22": "Di pertemuan kali ini, {nama} melanjutkan proses coding - menguji fitur yang sudah dibuat, men-debug masalah yang muncul, dan menambahkan lebih banyak fitur untuk melengkapi game.",
    "23": "Pada sesi kali ini, {nama} menambahkan fitur Game Pass ke dalam game, yang memungkinkan pemain untuk membuka konten spesial di dalam game.",
    "24": "Pada pertemuan ini, {nama} mempresentasikan game yang telah selesai kepada teman-teman sekelas."
  }
});
Object.assign(TEMPLATES_EN, {
  "Coding Explorer": {
    "1": "Today, {nama} learned that coding is a language that computers can understand. {nama} also practised writing code in the correct order - following an algorithm.",
    "2": "In this session, {nama} explored the effects of too much screen time and gadget use. {nama} also practised using Events and Loops in coding.",
    "3": "Today, {nama} learned about cyber bullying - what it is and how to handle it. {nama} also used Scratch to build a simple game.",
    "4": "In this class, {nama} learned how to use and take care of gadgets properly. {nama} was also introduced to Conditional statements - how coding can make decisions.",
    "5": "Today, {nama} was introduced to Virtual Reality (VR) - a technology that creates a fully immersive digital environment. {nama} explored what VR is, how it works, and experienced it first-hand.",
    "6": "In this session, {nama} learned about mindful messaging - thinking before you send. {nama} also practised controlling a virtual drone.",
    "7": "Today, {nama} learned what a 'Bug' is in programming - a mistake that needs fixing. {nama} also used the Glide feature in Scratch to create a game.",
    "8": "{nama} reviewed everything learned so far and completed Exam 1 for the Explorer level.",
    "9": "In this class, {nama} learned about the importance of perseverance - never giving up. {nama} also explored Conditional Loops in coding and played a Micro:bit Truth or Dare game.",
    "10": "Today, {nama} learned about spam and how to avoid it. {nama} also explored algorithms for problem-solving and used the Forever loop in their code.",
    "11": "In this session, {nama} learned about computer viruses and how to stay protected. {nama} also built an underwater aquarium scene using AR Cube.",
    "12": "Today, {nama} built a flying game in Scratch using everything they've learned so far.",
    "13": "In this class, {nama} explored how technology has developed over time. {nama} was also introduced to Variables in coding - a way to store and manage information.",
    "14": "Today, {nama} practised using Functions inside a VR environment - writing code to trigger actions and animations in the virtual world.",
    "15": "In this session, {nama} was introduced to Artificial Intelligence (AI) and got a first look at text-based coding using Python.",
    "16": "{nama} reviewed the previous lessons and completed Exam 2 for the Explorer level.",
    "17": "Today, {nama} learned about media balance - managing how much time we spend on screens. {nama} also built a game using Broadcast and Clone features in Scratch.",
    "18": "In this class, {nama} explored how the Internet of Things (IoT) makes life easier. {nama} was also introduced to Lists in coding.",
    "19": "Today, {nama} used Scratch to build a Soccer Game - coding the player movement, ball physics, and scoring system.",
    "20": "In this session, {nama} learned about Additive Design - how features are added step by step to build a complete game. {nama} started building a 'Create Your Own World' game - Part 1.",
    "21": "Today, {nama} started creating their own game, came up with an idea, and collected all the game assets needed.",
    "22": "In this class, {nama} continued working on their game - setting up the layout, coding the start screen, and writing the main game code.",
    "23": "Today, {nama} added lives, a score counter, the next level feature, and a game over screen to their game.",
    "24": "In this final session, {nama} finished and presented their game, got helpful feedback, fixed any bugs, and shared it with others.",
    "25": "Today, {nama} was introduced to Mobile Apps and explored MIT App Inventor - a tool for building apps without complex coding.",
    "26": "In this session, {nama} built a Clicker App and a Timer App using App Inventor.",
    "27": "Today, {nama} was introduced to how a Translator App works. {nama} used a Spinner and Speech Recognizer to build a Dictionary App.",
    "28": "In this class, {nama} built a Calculator app and a 'My Walk' app that tracks steps using a pedometer.",
    "29": "Today, {nama} built a drawing app and a Tic Tac Toe game using App Inventor.",
    "30": "In this session, {nama} explored ideas for a personal app project and started collecting the assets needed.",
    "31": "Today, {nama} worked on building their chosen app from scratch.",
    "32": "In this final class, {nama} finished and launched their app, then presented it to the group."
  },
  "Game Developer": {
    "1": "Today, {nama} was introduced to Construct 3 - a game-making tool. {nama} used behaviours to make a sprite character move and jump in a platform game.",
    "2": "In this session, {nama} built a maze layout and learned how to use Event Sheets to control what happens in the game.",
    "3": "Today, {nama} learned about Animation Frames and used the 8 Direction and Bound to Layout behaviours to animate a character.",
    "4": "In this class, {nama} added enemies and a score system to the game and created a next level feature.",
    "5": "Today, {nama} learned how to make a sprite aim and follow the mouse pointer. {nama} also explored the Physics behaviour.",
    "6": "In this session, {nama} added a Particle Effect to make the game look exciting and created Level 2 of the game.",
    "7": "{nama} reviewed all lessons from meetings 1 to 6.",
    "8": "{nama} completed the Game Developer Exam 1.",
    "9": "Today, {nama} built a bouncing ball game, made the paddle move, and set up floating blocks with instance variables.",
    "10": "In this class, {nama} added lives, a respawn system for the ball, and new levels to the game.",
    "11": "Today, {nama} added Start, Win, and Game Over layouts to the game, along with working buttons for each.",
    "12": "In this session, {nama} created a scrolling background, made the player character move, and set up random obstacle costumes.",
    "13": "Today, {nama} used Sprite Fonts for the Score and Life display and applied the Family Feature to manage game objects more efficiently.",
    "14": "In this class, {nama} added enemies using Instance Variables and added a Stardust particle effect to make the game feel more alive.",
    "15": "{nama} reviewed previous lessons in preparation for the exam.",
    "16": "{nama} completed the Game Developer Exam 2.",
    "17": "Today, {nama} designed the game layout using a Tilemap and made the player character move in a platformer-style game.",
    "18": "In this session, {nama} added obstacles, enemies, and collectible items to the game.",
    "19": "Today, {nama} added a next level feature and made items attach to the player character.",
    "20": "In this class, {nama} added an AI Enemy to the game and uploaded the finished game to a website.",
    "21": "Today, {nama} explored game ideas and collected assets for their own game project.",
    "22": "In this session, {nama} planned out their own game and set up the full layout - arranging the scenes, backgrounds, and key elements ready for coding.",
    "23": "Today, {nama} finished the game, fixed any bugs, and prepared it for launch.",
    "24": "{nama} launched their game and gave a presentation to the class."
  },
  "Code and Design with Roblox": {
    "1": "Today, {nama} learned about the hardware used in computers, was introduced to Roblox, explored the concept of game literacy, and set up Roblox Studio.",
    "2": "In this session, {nama} learned how to use the menus and keyboard shortcuts in Roblox Studio, was introduced to 3D modelling, and built a house model.",
    "3": "Today, {nama} explored modelling tools in more depth, built a model based on a Google Image reference, and learned about anchoring and how to save and collaborate on Roblox.",
    "4": "In this class, {nama} learned the parent & children concept in Roblox Studio, used the Toolbox, added a special effect, and completed the house project.",
    "5": "Today, {nama} designed a map background, learned how the Terrain Editor works, and started a new Roblox project.",
    "6": "In this session, {nama} learned how to use the Smooth and Flatten terrain tools and practised with the Brush plugin.",
    "7": "Today, {nama} learned about copyright and how to properly Publish a project to Roblox.",
    "8": "{nama} reviewed all previous lessons and completed the exam.",
    "9": "In this class, {nama} learned about the Rings of Responsibility, explored the Generate tool in the Terrain Editor, and built an underwater game world.",
    "10": "Today, {nama} learned about Solid Modelling tools, built an underwater house, and explored how gravity works in Roblox.",
    "11": "In this session, {nama} learned about screen time awareness, got started with scripting in Roblox, understood Properties, and wrote a script for a part.",
    "12": "Today, {nama} added a signboard with text, added sound effects, and changed the atmosphere of the game world.",
    "13": "In this class, {nama} learned about cyber bullying, explored Variables in coding, and understood the Instance.new() and wait() functions.",
    "14": "Today, {nama} learned about Loops and While Loops in coding, used a while loop in practice, and added a script to make an object move.",
    "15": "In this session, {nama} was introduced to animation in Roblox, learned how the animation tools work, and created an animation for a Farmland scene.",
    "16": "{nama} reviewed lessons 9–15 and completed the Roblox Explorer 2 exam.",
    "17": "Today, {nama} learned what Image Labels are used for, placed one on a part in the game, and created a name tag for a desk.",
    "18": "In this class, {nama} learned how traps work in games, built a laser beam trap using beam effects, and added a trap near the kitchen door.",
    "19": "Today, {nama} explored buildings and models for ideas, understood the rules for creating projects, created a draft design, and started modelling their building.",
    "20": "In this session, {nama} explored colour combinations, got modelling tips, and continued working on their building.",
    "21": "Today, {nama} added details to their model and completed the building.",
    "22": "In this class, {nama} learned about interactive parts and added scripts to make them work in the game.",
    "23": "Today, {nama} prepared a presentation for their project.",
    "24": "{nama} presented their finished project to the class."
  },
  "Interactive Mechanics on Roblox": {
    "1": "Today, {nama} designed a map layout, reviewed terrain tools, built the theme park environment, and changed the atmosphere of the map.",
    "2": "In this session, {nama} created an interactive model, learned how Events work in coding, and wrote a script to make a merry-go-round spin.",
    "3": "Today, {nama} was introduced to Photopea - an online design tool. {nama} created a simple shirt design, imported it into the Asset Manager, and wrote code to apply it to a character in the game.",
    "4": "In this class, {nama} created a storyline for an Escape game, prepared the clues, and started modelling the building.",
    "5": "Today, {nama} modelled a key for the game, learned about Conditional Statements - coding rules that make decisions - and wrote code to link the key with the door.",
    "6": "In this session, {nama} modelled a clue object, wrote code to show a text label, and added a light switch to the game.",
    "7": "Today, {nama} set up the atmosphere, modelled a headlamp, and the class played the game together after publishing it.",
    "8": "{nama} reviewed lessons 1–7 and completed the exam.",
    "9": "In this class, {nama} was introduced to Blender - a professional 3D design tool. {nama} learned the basic controls and created their first 3D model.",
    "10": "Today, {nama} built a bottle model and a player accessory in Blender, then exported the objects into Roblox Studio.",
    "11": "In this session, {nama} imported an object into their project, learned how Screen GUIs work, designed a GUI layout, and used the Tween Service to animate it.",
    "12": "Today, {nama} planned the Finding Object game, built the map and buildings, and added paintings using Image Labels.",
    "13": "In this class, {nama} continued building the interior of the map, decided where to hide the objects, and added a Screen GUI for clues.",
    "14": "Today, {nama} designed a low-poly barrel model and built the main object for the Finding Game in Blender.",
    "15": "In this session, {nama} exported many parts from Blender, created a GUI that appears when an object is found, and wrote code to allow players to pick up objects.",
    "16": "{nama} reviewed lessons 9–15 and completed the exam.",
    "17": "Today, {nama} learned how Roblox Places work, merged previous games into a lobby, and created images for badges and game passes.",
    "18": "In this class, {nama} learned how to structure thumbnails and game icons, added a Return button, and built an opening GUI.",
    "19": "Today, {nama} planned their own game, added a new Place to the lobby project, and started modelling.",
    "20": "In this session, {nama} continued modelling and used Blender to create additional models.",
    "21": "Today, {nama} added a GUI and a Tween animation to their game.",
    "22": "In this class, {nama} added mission code and a teleport script triggered by touch.",
    "23": "Today, {nama} created the project presentation and designed a thumbnail.",
    "24": "{nama} presented their final project to the class."
  },
  "Full Stack Programming on Roblox": {
    "1": "Today, {nama} was introduced to Roblox Studio. {nama} explored the interface, learned the basics of 3D modelling, and built an obby (obstacle) game.",
    "2": "In this session, {nama} learned what coding is and explored key concepts: Variables, Properties, and reusing code efficiently.",
    "3": "Today, {nama} practised the 3D modelling process and explored special effects tools in Roblox Studio.",
    "4": "In this class, {nama} discovered what an adventure game looks like. {nama} used the Terrain Editor and built terrain and a sell platform.",
    "5": "Today, {nama} learned how to set up a Leaderboard in the game and explored the concept of Functions in coding.",
    "6": "In this session, {nama} learned how Harvestable Items work in a game and applied Conditional Statements to control what happens in different situations.",
    "7": "Today, {nama} learned how a Sell Platform works - allowing players to exchange items for in-game currency.",
    "8": "{nama} reviewed all previous lessons and completed the exam for this unit.",
    "9": "In this class, {nama} created a custom player character and learned how to make it move properly in the game.",
    "10": "Today, {nama} explored the concept of Events in coding and built a Bullet model for the game.",
    "11": "In this session, {nama} wrote the code needed to spawn bullets in the game.",
    "12": "Today, {nama} learned how a story game flows, set up a Screen GUI, and applied Remote Events to connect the game's parts.",
    "13": "In this class, {nama} learned what a Module Script is and built a dynamic screen GUI that changes based on the game's situation.",
    "14": "Today, {nama} was introduced to animation in Roblox. {nama} created animations and applied them to the story game.",
    "15": "In this session, {nama} learned how to use a Click Detector, completed Task 2 of the game, and added effects for Task 3.",
    "16": "{nama} reviewed all lessons and completed the exam.",
    "17": "Today, {nama} explored game ideas, planned out their own game, and started designing the models and environment.",
    "18": "In this class, {nama} continued building and refining the game models - working on the map layout, props, and environment to bring the game world to life.",
    "19": "Today, {nama} started writing the core code for their own game - setting up variables, scripting key mechanics, and building the foundation of the game logic.",
    "20": "In this session, {nama} continued writing and testing the game's code - debugging issues, refining mechanics, and making sure everything works as intended.",
    "21": "Today, {nama} finished all the remaining coding for their game - polishing the logic, fixing final bugs, and ensuring a smooth experience for players.",
    "22": "In this class, {nama} showed their game progress to classmates and gave and received feedback.",
    "23": "Today, {nama} learned how players can earn Robux from their own game.",
    "24": "{nama} presented their completed game to the class."
  },
  "Advanced Lua Programming on Roblox": {
    "1": "Today, {nama} learned how a Battle Royale game is developed. {nama} helped prepare the game map, explored the multiplayer game loop, and added an interactive chest to the game.",
    "2": "In this session, {nama} learned how a lobby system works in games. {nama} also practiced using tables and for loops in Lua, and built a teleport system.",
    "3": "Today, {nama} created a sword model and wrote the coding to make it work in the game.",
    "4": "In this class, {nama} added a health potion and a gun to the game player.",
    "5": "Today, {nama} applied a timer module to the game and built a dynamic screen GUI to display information to players.",
    "6": "In this session, {nama} learned how losing players return to the lobby and how a match properly ends.",
    "7": "Today, {nama} learned how to clean up the game and reset it after a match ends, returning players to the intermission phase.",
    "8": "{nama} reviewed all previous lessons and completed the exam for this unit.",
    "9": "In this class, {nama} learned about the Cleaner Boat Simulator game flow and started preparing the game's materials.",
    "10": "Today, {nama} learned how to build a screen GUI that players can use to construct their boat.",
    "11": "In this session, {nama} explored how the placement system works - allowing players to place items in the game.",
    "12": "Today, {nama} wrote code to launch the boat and remove materials from it during gameplay.",
    "13": "In this class, {nama} learned how the boat collects trash and added a counter on screen to show how much trash has been collected.",
    "14": "Today, {nama} learned how to deactivate materials from the screen GUI and designed the quiz interface for upgrading the boat.",
    "15": "In this session, {nama} built the quiz system used to upgrade the boat and learned how the upgrade process works.",
    "16": "{nama} completed the review and exam for this unit.",
    "17": "Today, {nama} learned how to display math questions on the screen in the Math Obby game.",
    "18": "In this class, {nama} learned how to show answer choices and how the game checks if the player's answer is correct.",
    "19": "Today, {nama} explored game ideas, made a plan for their own game, and started building the environment and models.",
    "20": "In this session, {nama} continued working on the game models - refining the design, adding details, and making sure everything looks polished.",
    "21": "Today, {nama} started writing the core code for their game - setting up the game logic, variables, and the key functions needed to make it work.",
    "22": "In this class, {nama} continued coding their game - testing, debugging, and adding more features to bring the game closer to completion.",
    "23": "Today, {nama} added a Game Pass feature to their game, allowing players to unlock special in-game content.",
    "24": "{nama} presented their finished game to the class."
  }
});
